[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/135019631",
    "html_url": "https://github.com/jupyter/notebook/issues/339#issuecomment-135019631",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/339",
    "id": 135019631,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEzNTAxOTYzMQ==",
    "user": {
      "login": "Carreau",
      "id": 335567,
      "node_id": "MDQ6VXNlcjMzNTU2Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/335567?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Carreau",
      "html_url": "https://github.com/Carreau",
      "followers_url": "https://api.github.com/users/Carreau/followers",
      "following_url": "https://api.github.com/users/Carreau/following{/other_user}",
      "gists_url": "https://api.github.com/users/Carreau/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Carreau/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Carreau/subscriptions",
      "organizations_url": "https://api.github.com/users/Carreau/orgs",
      "repos_url": "https://api.github.com/users/Carreau/repos",
      "events_url": "https://api.github.com/users/Carreau/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Carreau/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-26T13:27:31Z",
    "updated_at": "2015-08-26T13:27:31Z",
    "author_association": "MEMBER",
    "body": "The scripts should be done by setup.py on [theses lines](https://github.com/jupyter/notebook/blob/656628cbe6ae9996b6fc30028322b85bcbb76137/setup.py#L182-L183) but maybe it make sens to ship the scripts in the sdist. \nI'm not sure. \n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/135462982",
    "html_url": "https://github.com/jupyter/notebook/issues/339#issuecomment-135462982",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/339",
    "id": 135462982,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEzNTQ2Mjk4Mg==",
    "user": {
      "login": "toddrme2178",
      "id": 4181796,
      "node_id": "MDQ6VXNlcjQxODE3OTY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4181796?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/toddrme2178",
      "html_url": "https://github.com/toddrme2178",
      "followers_url": "https://api.github.com/users/toddrme2178/followers",
      "following_url": "https://api.github.com/users/toddrme2178/following{/other_user}",
      "gists_url": "https://api.github.com/users/toddrme2178/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/toddrme2178/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/toddrme2178/subscriptions",
      "organizations_url": "https://api.github.com/users/toddrme2178/orgs",
      "repos_url": "https://api.github.com/users/toddrme2178/repos",
      "events_url": "https://api.github.com/users/toddrme2178/events{/privacy}",
      "received_events_url": "https://api.github.com/users/toddrme2178/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-27T15:06:15Z",
    "updated_at": "2015-08-27T15:06:15Z",
    "author_association": "CONTRIBUTOR",
    "body": "The scripts are not getting installed at all for me under 4.0.4.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/136796438",
    "html_url": "https://github.com/jupyter/notebook/issues/339#issuecomment-136796438",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/339",
    "id": 136796438,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEzNjc5NjQzOA==",
    "user": {
      "login": "flacjacket",
      "id": 681093,
      "node_id": "MDQ6VXNlcjY4MTA5Mw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/681093?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/flacjacket",
      "html_url": "https://github.com/flacjacket",
      "followers_url": "https://api.github.com/users/flacjacket/followers",
      "following_url": "https://api.github.com/users/flacjacket/following{/other_user}",
      "gists_url": "https://api.github.com/users/flacjacket/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/flacjacket/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/flacjacket/subscriptions",
      "organizations_url": "https://api.github.com/users/flacjacket/orgs",
      "repos_url": "https://api.github.com/users/flacjacket/repos",
      "events_url": "https://api.github.com/users/flacjacket/events{/privacy}",
      "received_events_url": "https://api.github.com/users/flacjacket/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-01T17:02:46Z",
    "updated_at": "2015-09-02T18:41:57Z",
    "author_association": "NONE",
    "body": "I've also run into this, both here and with qtconsole.\n\nEdit: acutally, even though qtconsole has a similar setup.py, the scripts directory does show up in that PyPI package, ignore that\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/138562274",
    "html_url": "https://github.com/jupyter/notebook/issues/339#issuecomment-138562274",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/339",
    "id": 138562274,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEzODU2MjI3NA==",
    "user": {
      "login": "asergi",
      "id": 325166,
      "node_id": "MDQ6VXNlcjMyNTE2Ng==",
      "avatar_url": "https://avatars.githubusercontent.com/u/325166?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/asergi",
      "html_url": "https://github.com/asergi",
      "followers_url": "https://api.github.com/users/asergi/followers",
      "following_url": "https://api.github.com/users/asergi/following{/other_user}",
      "gists_url": "https://api.github.com/users/asergi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/asergi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/asergi/subscriptions",
      "organizations_url": "https://api.github.com/users/asergi/orgs",
      "repos_url": "https://api.github.com/users/asergi/repos",
      "events_url": "https://api.github.com/users/asergi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/asergi/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-08T13:42:15Z",
    "updated_at": "2015-09-14T18:18:14Z",
    "author_association": "NONE",
    "body": "I can confirm this bug as well.\nWithout the `scripts` directory the bin scripts are not generated. In fact:\n\n```\n% jupyter notebook            \njupyter: 'notebook' is not a Jupyter command\n```\n\nThe GitHub version is not affetcted by this bug. Only the PyPI tarball.\nThanks in advance.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/140157792",
    "html_url": "https://github.com/jupyter/notebook/issues/339#issuecomment-140157792",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/339",
    "id": 140157792,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0MDE1Nzc5Mg==",
    "user": {
      "login": "Carreau",
      "id": 335567,
      "node_id": "MDQ6VXNlcjMzNTU2Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/335567?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Carreau",
      "html_url": "https://github.com/Carreau",
      "followers_url": "https://api.github.com/users/Carreau/followers",
      "following_url": "https://api.github.com/users/Carreau/following{/other_user}",
      "gists_url": "https://api.github.com/users/Carreau/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Carreau/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Carreau/subscriptions",
      "organizations_url": "https://api.github.com/users/Carreau/orgs",
      "repos_url": "https://api.github.com/users/Carreau/repos",
      "events_url": "https://api.github.com/users/Carreau/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Carreau/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-14T17:48:00Z",
    "updated_at": "2015-09-14T17:48:00Z",
    "author_association": "MEMBER",
    "body": "@minrk could this have been fixed by one of your recent changes in setup.py ?\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/140163615",
    "html_url": "https://github.com/jupyter/notebook/issues/339#issuecomment-140163615",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/339",
    "id": 140163615,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0MDE2MzYxNQ==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-14T18:12:01Z",
    "updated_at": "2015-09-14T18:12:01Z",
    "author_association": "MEMBER",
    "body": "Weeeird.... When I run sdist it includes them. I don't think this is fixed by a change in setup.py, but maybe something went wrong when building the last sdist. We have a bugfix release that we should be pushing out this week, I'll make sure it gets the scripts.\n\nInstalling with `pip` shouldn't need the scripts, since they aren't used when setuptools is involved.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/142212453",
    "html_url": "https://github.com/jupyter/notebook/issues/339#issuecomment-142212453",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/339",
    "id": 142212453,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0MjIxMjQ1Mw==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-22T08:34:19Z",
    "updated_at": "2015-09-22T08:34:19Z",
    "author_association": "MEMBER",
    "body": "Released 4.0.5 and verified that scripts are in the sdist.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/142363678",
    "html_url": "https://github.com/jupyter/notebook/issues/339#issuecomment-142363678",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/339",
    "id": 142363678,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0MjM2MzY3OA==",
    "user": {
      "login": "flacjacket",
      "id": 681093,
      "node_id": "MDQ6VXNlcjY4MTA5Mw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/681093?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/flacjacket",
      "html_url": "https://github.com/flacjacket",
      "followers_url": "https://api.github.com/users/flacjacket/followers",
      "following_url": "https://api.github.com/users/flacjacket/following{/other_user}",
      "gists_url": "https://api.github.com/users/flacjacket/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/flacjacket/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/flacjacket/subscriptions",
      "organizations_url": "https://api.github.com/users/flacjacket/orgs",
      "repos_url": "https://api.github.com/users/flacjacket/repos",
      "events_url": "https://api.github.com/users/flacjacket/events{/privacy}",
      "received_events_url": "https://api.github.com/users/flacjacket/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-22T17:51:11Z",
    "updated_at": "2015-09-22T17:51:11Z",
    "author_association": "NONE",
    "body": "From the PyPI upload [here](https://pypi.python.org/packages/source/n/notebook/notebook-4.0.5.tar.gz#md5=8d13252a5afaf07380d21cb408040d22) the scripts aren't in the package.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/142365378",
    "html_url": "https://github.com/jupyter/notebook/issues/339#issuecomment-142365378",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/339",
    "id": 142365378,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0MjM2NTM3OA==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-22T17:58:17Z",
    "updated_at": "2015-09-22T17:58:17Z",
    "author_association": "MEMBER",
    "body": "WTF, I tested and verified that it was working, \n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/142368211",
    "html_url": "https://github.com/jupyter/notebook/issues/339#issuecomment-142368211",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/339",
    "id": 142368211,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0MjM2ODIxMQ==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-22T18:09:37Z",
    "updated_at": "2015-09-22T18:09:37Z",
    "author_association": "MEMBER",
    "body": "Ah, okay. I see that setuptools ruins upload. Fixing...\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/142369542",
    "html_url": "https://github.com/jupyter/notebook/issues/339#issuecomment-142369542",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/339",
    "id": 142369542,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0MjM2OTU0Mg==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-22T18:15:30Z",
    "updated_at": "2015-09-22T18:15:30Z",
    "author_association": "MEMBER",
    "body": "@flacjacket sorry about that, and thanks for catching it again. Fixed sdists for 4.0.5 are now on PyPI.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/142370090",
    "html_url": "https://github.com/jupyter/notebook/issues/339#issuecomment-142370090",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/339",
    "id": 142370090,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0MjM3MDA5MA==",
    "user": {
      "login": "flacjacket",
      "id": 681093,
      "node_id": "MDQ6VXNlcjY4MTA5Mw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/681093?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/flacjacket",
      "html_url": "https://github.com/flacjacket",
      "followers_url": "https://api.github.com/users/flacjacket/followers",
      "following_url": "https://api.github.com/users/flacjacket/following{/other_user}",
      "gists_url": "https://api.github.com/users/flacjacket/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/flacjacket/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/flacjacket/subscriptions",
      "organizations_url": "https://api.github.com/users/flacjacket/orgs",
      "repos_url": "https://api.github.com/users/flacjacket/repos",
      "events_url": "https://api.github.com/users/flacjacket/events{/privacy}",
      "received_events_url": "https://api.github.com/users/flacjacket/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-22T18:17:52Z",
    "updated_at": "2015-09-22T18:17:52Z",
    "author_association": "NONE",
    "body": "Great, thanks for the quick fix\n\nOn Tue, Sep 22, 2015, 13:15 Min RK notifications@github.com wrote:\n\n> @flacjacket https://github.com/flacjacket sorry about that, and thanks\n> for catching it again. Fixed sdists for 4.0.5 are now on PyPI.\n> \n> —\n> Reply to this email directly or view it on GitHub\n> https://github.com/jupyter/notebook/issues/339#issuecomment-142369542.\n",
    "performed_via_github_app": null
  }
]
