[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/362575099",
    "html_url": "https://github.com/jupyter/notebook/pull/3287#issuecomment-362575099",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3287",
    "id": 362575099,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM2MjU3NTA5OQ==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-02-02T12:35:53Z",
    "updated_at": "2018-02-02T12:35:53Z",
    "author_association": "MEMBER",
    "body": "The test failure is unrelated - a broken link in the docs. I've opened #3292 to figure out if we can be smarter about checking the links.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/362578910",
    "html_url": "https://github.com/jupyter/notebook/pull/3287#issuecomment-362578910",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3287",
    "id": 362578910,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM2MjU3ODkxMA==",
    "user": {
      "login": "damianavila",
      "id": 1640669,
      "node_id": "MDQ6VXNlcjE2NDA2Njk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1640669?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/damianavila",
      "html_url": "https://github.com/damianavila",
      "followers_url": "https://api.github.com/users/damianavila/followers",
      "following_url": "https://api.github.com/users/damianavila/following{/other_user}",
      "gists_url": "https://api.github.com/users/damianavila/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/damianavila/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/damianavila/subscriptions",
      "organizations_url": "https://api.github.com/users/damianavila/orgs",
      "repos_url": "https://api.github.com/users/damianavila/repos",
      "events_url": "https://api.github.com/users/damianavila/events{/privacy}",
      "received_events_url": "https://api.github.com/users/damianavila/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-02-02T12:55:34Z",
    "updated_at": "2018-02-02T12:55:34Z",
    "author_association": "MEMBER",
    "body": "> The test failure is unrelated - a broken link in the docs. I've opened #3292 to figure out if we can be smarter about checking the links.\r\n\r\nThanks! \r\nWhat do you suggest to do in the meantime? Remove the offending link? Merge as is? Thoughts welcome :wink:",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/362579016",
    "html_url": "https://github.com/jupyter/notebook/pull/3287#issuecomment-362579016",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3287",
    "id": 362579016,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM2MjU3OTAxNg==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-02-02T12:56:07Z",
    "updated_at": "2018-02-02T12:56:07Z",
    "author_association": "MEMBER",
    "body": "I've made #3293 to fix the link, and merged this one.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/362579067",
    "html_url": "https://github.com/jupyter/notebook/pull/3287#issuecomment-362579067",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3287",
    "id": 362579067,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM2MjU3OTA2Nw==",
    "user": {
      "login": "damianavila",
      "id": 1640669,
      "node_id": "MDQ6VXNlcjE2NDA2Njk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1640669?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/damianavila",
      "html_url": "https://github.com/damianavila",
      "followers_url": "https://api.github.com/users/damianavila/followers",
      "following_url": "https://api.github.com/users/damianavila/following{/other_user}",
      "gists_url": "https://api.github.com/users/damianavila/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/damianavila/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/damianavila/subscriptions",
      "organizations_url": "https://api.github.com/users/damianavila/orgs",
      "repos_url": "https://api.github.com/users/damianavila/repos",
      "events_url": "https://api.github.com/users/damianavila/events{/privacy}",
      "received_events_url": "https://api.github.com/users/damianavila/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-02-02T12:56:21Z",
    "updated_at": "2018-02-02T12:56:35Z",
    "author_association": "MEMBER",
    "body": "> What do you suggest to do in the meantime? Remove the offending link? Merge as is? Thoughts welcome ðŸ˜‰\r\n\r\nWell, you pressed the merge button at the same time I was submitting my answer, funny!",
    "performed_via_github_app": null
  }
]
