[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/405358051",
    "html_url": "https://github.com/jupyter/notebook/issues/3774#issuecomment-405358051",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3774",
    "id": 405358051,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQwNTM1ODA1MQ==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-07-16T19:41:18Z",
    "updated_at": "2018-07-16T19:41:18Z",
    "author_association": "MEMBER",
    "body": "How are you starting the notebook? It's fairly common to set environment variables in a file like `.bashrc`, but if you don't launch the notebook from bash, it doesn't inherit variables set that way.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/405364756",
    "html_url": "https://github.com/jupyter/notebook/issues/3774#issuecomment-405364756",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3774",
    "id": 405364756,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQwNTM2NDc1Ng==",
    "user": {
      "login": "kdheepak",
      "id": 1813121,
      "node_id": "MDQ6VXNlcjE4MTMxMjE=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1813121?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kdheepak",
      "html_url": "https://github.com/kdheepak",
      "followers_url": "https://api.github.com/users/kdheepak/followers",
      "following_url": "https://api.github.com/users/kdheepak/following{/other_user}",
      "gists_url": "https://api.github.com/users/kdheepak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kdheepak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kdheepak/subscriptions",
      "organizations_url": "https://api.github.com/users/kdheepak/orgs",
      "repos_url": "https://api.github.com/users/kdheepak/repos",
      "events_url": "https://api.github.com/users/kdheepak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kdheepak/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-07-16T20:05:31Z",
    "updated_at": "2018-07-16T20:05:31Z",
    "author_association": "NONE",
    "body": "@takluyver Thanks for the quick reply. Starting `jupyter` from `bash` and it seems to work! Starting from `zsh` however it does not. I have the following in my `~/.zshrc`.\r\n\r\n```bash\r\nsource ~/.bash_profile\r\n```\r\n\r\nMy `~/.bash_profile` has the following\r\n\r\n```bash\r\nif [ -f $HOME/.bashrc ]; then\r\n        source $HOME/.bashrc\r\nfi\r\n```\r\n\r\nAnd my `~/.bashrc` has the following\r\n\r\n```bash\r\nexport DYLD_FALLBACK_LIBRARY_PATH=${XPRESSDIR}/lib:${DYLD_FALLBACK_LIBRARY_PATH}\r\n```\r\n\r\nIt does seem like this is isolated to my computer, and specifically just the shell I'm using. Thanks for your comment, I didn't think to check that. I'll be able to figure it out now, I'm just going to have to debug my environment variables scripts. ",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/405720696",
    "html_url": "https://github.com/jupyter/notebook/issues/3774#issuecomment-405720696",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3774",
    "id": 405720696,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQwNTcyMDY5Ng==",
    "user": {
      "login": "kdheepak",
      "id": 1813121,
      "node_id": "MDQ6VXNlcjE4MTMxMjE=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1813121?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kdheepak",
      "html_url": "https://github.com/kdheepak",
      "followers_url": "https://api.github.com/users/kdheepak/followers",
      "following_url": "https://api.github.com/users/kdheepak/following{/other_user}",
      "gists_url": "https://api.github.com/users/kdheepak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kdheepak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kdheepak/subscriptions",
      "organizations_url": "https://api.github.com/users/kdheepak/orgs",
      "repos_url": "https://api.github.com/users/kdheepak/repos",
      "events_url": "https://api.github.com/users/kdheepak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kdheepak/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-07-17T20:41:55Z",
    "updated_at": "2018-07-17T20:41:55Z",
    "author_association": "NONE",
    "body": "I think I have to reopen this issue. On my Mac, when I run `jupyter notebook` there is no issue. However when I run `jupyter lab`, regardless of whether I use the notebook or the lab interface, the `DYLD_FALLBACK_LIBRARY_PATH` is unset. Proof with screenshots. On the left, I'm running `jupyter notebook` (highlighted) which opens `localhost:8888` and on the right I'm running `jupyter lab` (highlighted) which open `localhost:8889`.\r\n\r\n<img width=\"1680\" alt=\"screen shot 2018-07-17 at 2 35 29 pm\" src=\"https://user-images.githubusercontent.com/1813121/42844030-06353e84-89cf-11e8-8bd5-53d9a43b2f48.png\">\r\n\r\nThe following is screenshots from all combinations. I use the same version of Python (version 3.6.2) to get the value of the environment variable `DYLD_FALLBACK_LIBRARY_PATH`. \r\n\r\n<img width=\"1680\" alt=\"screen shot 2018-07-17 at 2 34 53 pm\" src=\"https://user-images.githubusercontent.com/1813121/42844122-3c00725e-89cf-11e8-82e3-6dad2fe6a573.png\">\r\n\r\nIn the instances of the notebook and the lab that was started by running `jupyter lab`, the value of the envrionment variable is set to `None`. ",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/405721993",
    "html_url": "https://github.com/jupyter/notebook/issues/3774#issuecomment-405721993",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3774",
    "id": 405721993,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQwNTcyMTk5Mw==",
    "user": {
      "login": "kdheepak",
      "id": 1813121,
      "node_id": "MDQ6VXNlcjE4MTMxMjE=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1813121?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kdheepak",
      "html_url": "https://github.com/kdheepak",
      "followers_url": "https://api.github.com/users/kdheepak/followers",
      "following_url": "https://api.github.com/users/kdheepak/following{/other_user}",
      "gists_url": "https://api.github.com/users/kdheepak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kdheepak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kdheepak/subscriptions",
      "organizations_url": "https://api.github.com/users/kdheepak/orgs",
      "repos_url": "https://api.github.com/users/kdheepak/repos",
      "events_url": "https://api.github.com/users/kdheepak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kdheepak/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-07-17T20:46:18Z",
    "updated_at": "2018-07-17T20:46:18Z",
    "author_association": "NONE",
    "body": "I've opened an issue on the jupyterlab repository instead.",
    "performed_via_github_app": null
  }
]
