[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/479029068",
    "html_url": "https://github.com/jupyter/notebook/issues/4532#issuecomment-479029068",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4532",
    "id": 479029068,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3OTAyOTA2OA==",
    "user": {
      "login": "trvrmcs",
      "id": 45498500,
      "node_id": "MDQ6VXNlcjQ1NDk4NTAw",
      "avatar_url": "https://avatars.githubusercontent.com/u/45498500?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/trvrmcs",
      "html_url": "https://github.com/trvrmcs",
      "followers_url": "https://api.github.com/users/trvrmcs/followers",
      "following_url": "https://api.github.com/users/trvrmcs/following{/other_user}",
      "gists_url": "https://api.github.com/users/trvrmcs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/trvrmcs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/trvrmcs/subscriptions",
      "organizations_url": "https://api.github.com/users/trvrmcs/orgs",
      "repos_url": "https://api.github.com/users/trvrmcs/repos",
      "events_url": "https://api.github.com/users/trvrmcs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/trvrmcs/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-04-02T14:41:28Z",
    "updated_at": "2019-04-02T14:41:28Z",
    "author_association": "NONE",
    "body": "Just encountered this myself - this is a recent breaking change.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/479071784",
    "html_url": "https://github.com/jupyter/notebook/issues/4532#issuecomment-479071784",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4532",
    "id": 479071784,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3OTA3MTc4NA==",
    "user": {
      "login": "kevin-bates",
      "id": 22599560,
      "node_id": "MDQ6VXNlcjIyNTk5NTYw",
      "avatar_url": "https://avatars.githubusercontent.com/u/22599560?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevin-bates",
      "html_url": "https://github.com/kevin-bates",
      "followers_url": "https://api.github.com/users/kevin-bates/followers",
      "following_url": "https://api.github.com/users/kevin-bates/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevin-bates/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevin-bates/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevin-bates/subscriptions",
      "organizations_url": "https://api.github.com/users/kevin-bates/orgs",
      "repos_url": "https://api.github.com/users/kevin-bates/repos",
      "events_url": "https://api.github.com/users/kevin-bates/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevin-bates/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-04-02T16:09:35Z",
    "updated_at": "2019-04-02T16:09:35Z",
    "author_association": "MEMBER",
    "body": "This looks like an instance of https://github.com/ipython/ipython/issues/11659 and not a notebook issue itself.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/479307395",
    "html_url": "https://github.com/jupyter/notebook/issues/4532#issuecomment-479307395",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4532",
    "id": 479307395,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3OTMwNzM5NQ==",
    "user": {
      "login": "aakhmetz",
      "id": 2173206,
      "node_id": "MDQ6VXNlcjIxNzMyMDY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2173206?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/aakhmetz",
      "html_url": "https://github.com/aakhmetz",
      "followers_url": "https://api.github.com/users/aakhmetz/followers",
      "following_url": "https://api.github.com/users/aakhmetz/following{/other_user}",
      "gists_url": "https://api.github.com/users/aakhmetz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/aakhmetz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/aakhmetz/subscriptions",
      "organizations_url": "https://api.github.com/users/aakhmetz/orgs",
      "repos_url": "https://api.github.com/users/aakhmetz/repos",
      "events_url": "https://api.github.com/users/aakhmetz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/aakhmetz/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-04-03T02:36:57Z",
    "updated_at": "2019-04-03T02:36:57Z",
    "author_association": "NONE",
    "body": "Thank you @kevin-bates! And it looks like the patch will come out soon ",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/490157790",
    "html_url": "https://github.com/jupyter/notebook/issues/4532#issuecomment-490157790",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4532",
    "id": 490157790,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ5MDE1Nzc5MA==",
    "user": {
      "login": "makeyourownalgorithmicart",
      "id": 29485854,
      "node_id": "MDQ6VXNlcjI5NDg1ODU0",
      "avatar_url": "https://avatars.githubusercontent.com/u/29485854?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/makeyourownalgorithmicart",
      "html_url": "https://github.com/makeyourownalgorithmicart",
      "followers_url": "https://api.github.com/users/makeyourownalgorithmicart/followers",
      "following_url": "https://api.github.com/users/makeyourownalgorithmicart/following{/other_user}",
      "gists_url": "https://api.github.com/users/makeyourownalgorithmicart/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/makeyourownalgorithmicart/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/makeyourownalgorithmicart/subscriptions",
      "organizations_url": "https://api.github.com/users/makeyourownalgorithmicart/orgs",
      "repos_url": "https://api.github.com/users/makeyourownalgorithmicart/repos",
      "events_url": "https://api.github.com/users/makeyourownalgorithmicart/events{/privacy}",
      "received_events_url": "https://api.github.com/users/makeyourownalgorithmicart/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-05-07T16:41:58Z",
    "updated_at": "2019-05-07T16:41:58Z",
    "author_association": "NONE",
    "body": "I too am seeing this error with %%time \r\n\r\n```\r\nconda list ipython\r\n# packages in environment at /Users/tariq/anaconda3:\r\n#\r\n# Name                    Version                   Build  Channel\r\nipython                   7.4.0            py37h39e3cac_0  \r\nipython_genutils          0.2.0                    py37_0  \r\n\r\n```",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/501284967",
    "html_url": "https://github.com/jupyter/notebook/issues/4532#issuecomment-501284967",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4532",
    "id": 501284967,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUwMTI4NDk2Nw==",
    "user": {
      "login": "sparkingarthur",
      "id": 16410193,
      "node_id": "MDQ6VXNlcjE2NDEwMTkz",
      "avatar_url": "https://avatars.githubusercontent.com/u/16410193?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sparkingarthur",
      "html_url": "https://github.com/sparkingarthur",
      "followers_url": "https://api.github.com/users/sparkingarthur/followers",
      "following_url": "https://api.github.com/users/sparkingarthur/following{/other_user}",
      "gists_url": "https://api.github.com/users/sparkingarthur/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sparkingarthur/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sparkingarthur/subscriptions",
      "organizations_url": "https://api.github.com/users/sparkingarthur/orgs",
      "repos_url": "https://api.github.com/users/sparkingarthur/repos",
      "events_url": "https://api.github.com/users/sparkingarthur/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sparkingarthur/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-06-12T13:56:43Z",
    "updated_at": "2019-06-12T13:56:43Z",
    "author_association": "NONE",
    "body": "same with ipython version 7.4.0",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/502664527",
    "html_url": "https://github.com/jupyter/notebook/issues/4532#issuecomment-502664527",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4532",
    "id": 502664527,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUwMjY2NDUyNw==",
    "user": {
      "login": "1JasonZhang",
      "id": 31090535,
      "node_id": "MDQ6VXNlcjMxMDkwNTM1",
      "avatar_url": "https://avatars.githubusercontent.com/u/31090535?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/1JasonZhang",
      "html_url": "https://github.com/1JasonZhang",
      "followers_url": "https://api.github.com/users/1JasonZhang/followers",
      "following_url": "https://api.github.com/users/1JasonZhang/following{/other_user}",
      "gists_url": "https://api.github.com/users/1JasonZhang/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/1JasonZhang/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/1JasonZhang/subscriptions",
      "organizations_url": "https://api.github.com/users/1JasonZhang/orgs",
      "repos_url": "https://api.github.com/users/1JasonZhang/repos",
      "events_url": "https://api.github.com/users/1JasonZhang/events{/privacy}",
      "received_events_url": "https://api.github.com/users/1JasonZhang/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-06-17T12:36:03Z",
    "updated_at": "2019-06-17T12:36:03Z",
    "author_association": "NONE",
    "body": "what time to fix this bug?",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/502665651",
    "html_url": "https://github.com/jupyter/notebook/issues/4532#issuecomment-502665651",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4532",
    "id": 502665651,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUwMjY2NTY1MQ==",
    "user": {
      "login": "aakhmetz",
      "id": 2173206,
      "node_id": "MDQ6VXNlcjIxNzMyMDY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2173206?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/aakhmetz",
      "html_url": "https://github.com/aakhmetz",
      "followers_url": "https://api.github.com/users/aakhmetz/followers",
      "following_url": "https://api.github.com/users/aakhmetz/following{/other_user}",
      "gists_url": "https://api.github.com/users/aakhmetz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/aakhmetz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/aakhmetz/subscriptions",
      "organizations_url": "https://api.github.com/users/aakhmetz/orgs",
      "repos_url": "https://api.github.com/users/aakhmetz/repos",
      "events_url": "https://api.github.com/users/aakhmetz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/aakhmetz/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-06-17T12:39:49Z",
    "updated_at": "2019-06-17T12:39:49Z",
    "author_association": "NONE",
    "body": "following the message from kevin-bates, I think, the bug was fixed. At least, it works for me now\r\n\r\n===\r\n```\r\n# Name                    Version                   Build  Channel\r\nipython                   7.5.0            py37h39e3cac_0  \r\nipython_genutils          0.2.0                    py37_0 \r\n```\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/508282054",
    "html_url": "https://github.com/jupyter/notebook/issues/4532#issuecomment-508282054",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4532",
    "id": 508282054,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUwODI4MjA1NA==",
    "user": {
      "login": "royalosyin",
      "id": 18584202,
      "node_id": "MDQ6VXNlcjE4NTg0MjAy",
      "avatar_url": "https://avatars.githubusercontent.com/u/18584202?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/royalosyin",
      "html_url": "https://github.com/royalosyin",
      "followers_url": "https://api.github.com/users/royalosyin/followers",
      "following_url": "https://api.github.com/users/royalosyin/following{/other_user}",
      "gists_url": "https://api.github.com/users/royalosyin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/royalosyin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/royalosyin/subscriptions",
      "organizations_url": "https://api.github.com/users/royalosyin/orgs",
      "repos_url": "https://api.github.com/users/royalosyin/repos",
      "events_url": "https://api.github.com/users/royalosyin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/royalosyin/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-07-03T23:00:10Z",
    "updated_at": "2019-07-03T23:00:10Z",
    "author_association": "NONE",
    "body": "Reinstall using pip instead of conda on Windows 10. It works now.\r\npip install ipython -U\r\npip install ipython_genutils  -U\r\n\r\nSuccessfully installed ipython-7.6.1\r\nSuccessfully installed ipython_genutils-0.2.0",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/524855563",
    "html_url": "https://github.com/jupyter/notebook/issues/4532#issuecomment-524855563",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4532",
    "id": 524855563,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUyNDg1NTU2Mw==",
    "user": {
      "login": "schneiderfelipe",
      "id": 37125,
      "node_id": "MDQ6VXNlcjM3MTI1",
      "avatar_url": "https://avatars.githubusercontent.com/u/37125?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/schneiderfelipe",
      "html_url": "https://github.com/schneiderfelipe",
      "followers_url": "https://api.github.com/users/schneiderfelipe/followers",
      "following_url": "https://api.github.com/users/schneiderfelipe/following{/other_user}",
      "gists_url": "https://api.github.com/users/schneiderfelipe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/schneiderfelipe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/schneiderfelipe/subscriptions",
      "organizations_url": "https://api.github.com/users/schneiderfelipe/orgs",
      "repos_url": "https://api.github.com/users/schneiderfelipe/repos",
      "events_url": "https://api.github.com/users/schneiderfelipe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/schneiderfelipe/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-08-26T13:14:41Z",
    "updated_at": "2019-08-26T13:14:41Z",
    "author_association": "NONE",
    "body": "Same here, using pip (just updated as @royalosyin suggested, current ipython version is 7.7.0):\r\n\r\n```python3\r\nIn [1]: import numpy as np\r\nIn [2]: size = 20\r\nIn [3]: D = np.random.rand(size, size)\r\nIn [4]: I = np.random.rand(size, size, size, size)\r\nIn [5]: %%timeit\r\n   ...: Gloop = np.zeros((size, size))\r\n   ...: for p in range(size):\r\n   ...:     for q in range(size):\r\n   ...:         for r in range(size):\r\n   ...:             for s in range(size):\r\n   ...:                 Gloop[p, q] += (2 * I[p, q, r, s] - I[p, r, q, s]) * D[r, s]\r\n   ...:\r\n234 ms ± 1.07 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)\r\nIn [6]: Gloop\r\n---------------------------------------------------------------------------\r\nNameError                                 Traceback (most recent call last)\r\n<ipython-input-7-b2508f9fc33d> in <module>\r\n----> 1 Gloop\r\n\r\nNameError: name 'Gloop' is not defined\r\n```\r\n\r\nI'm using Ubuntu:\r\n\r\n```bash\r\n% uname -a\r\nLinux mothership 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux\r\n% python3 --version\r\nPython 3.6.8\r\n% pip3 --version\r\npip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)\r\n% ipython3 --version\r\n7.7.0\r\n```",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/527275419",
    "html_url": "https://github.com/jupyter/notebook/issues/4532#issuecomment-527275419",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4532",
    "id": 527275419,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUyNzI3NTQxOQ==",
    "user": {
      "login": "minda163",
      "id": 33540791,
      "node_id": "MDQ6VXNlcjMzNTQwNzkx",
      "avatar_url": "https://avatars.githubusercontent.com/u/33540791?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minda163",
      "html_url": "https://github.com/minda163",
      "followers_url": "https://api.github.com/users/minda163/followers",
      "following_url": "https://api.github.com/users/minda163/following{/other_user}",
      "gists_url": "https://api.github.com/users/minda163/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minda163/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minda163/subscriptions",
      "organizations_url": "https://api.github.com/users/minda163/orgs",
      "repos_url": "https://api.github.com/users/minda163/repos",
      "events_url": "https://api.github.com/users/minda163/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minda163/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-09-03T02:00:16Z",
    "updated_at": "2019-09-03T02:00:16Z",
    "author_association": "NONE",
    "body": "same error......",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/527279129",
    "html_url": "https://github.com/jupyter/notebook/issues/4532#issuecomment-527279129",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4532",
    "id": 527279129,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUyNzI3OTEyOQ==",
    "user": {
      "login": "aakhmetz",
      "id": 2173206,
      "node_id": "MDQ6VXNlcjIxNzMyMDY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2173206?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/aakhmetz",
      "html_url": "https://github.com/aakhmetz",
      "followers_url": "https://api.github.com/users/aakhmetz/followers",
      "following_url": "https://api.github.com/users/aakhmetz/following{/other_user}",
      "gists_url": "https://api.github.com/users/aakhmetz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/aakhmetz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/aakhmetz/subscriptions",
      "organizations_url": "https://api.github.com/users/aakhmetz/orgs",
      "repos_url": "https://api.github.com/users/aakhmetz/repos",
      "events_url": "https://api.github.com/users/aakhmetz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/aakhmetz/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-09-03T02:22:45Z",
    "updated_at": "2019-09-03T02:22:45Z",
    "author_association": "NONE",
    "body": "@schneiderfelipe you code works for me if I use ```%%time``` instead of ```%%timeit``` (the former is a subject of this thread). I confirm your code does not work with ```%%timeit```. Maybe you can open another issue regarding an unfortunate difference of these two ",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/667556125",
    "html_url": "https://github.com/jupyter/notebook/issues/4532#issuecomment-667556125",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4532",
    "id": 667556125,
    "node_id": "MDEyOklzc3VlQ29tbWVudDY2NzU1NjEyNQ==",
    "user": {
      "login": "dazzle-me",
      "id": 57013219,
      "node_id": "MDQ6VXNlcjU3MDEzMjE5",
      "avatar_url": "https://avatars.githubusercontent.com/u/57013219?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dazzle-me",
      "html_url": "https://github.com/dazzle-me",
      "followers_url": "https://api.github.com/users/dazzle-me/followers",
      "following_url": "https://api.github.com/users/dazzle-me/following{/other_user}",
      "gists_url": "https://api.github.com/users/dazzle-me/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dazzle-me/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dazzle-me/subscriptions",
      "organizations_url": "https://api.github.com/users/dazzle-me/orgs",
      "repos_url": "https://api.github.com/users/dazzle-me/repos",
      "events_url": "https://api.github.com/users/dazzle-me/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dazzle-me/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-08-01T16:31:08Z",
    "updated_at": "2020-08-01T16:31:58Z",
    "author_association": "NONE",
    "body": "I just encountered the same problem when I tried to measure the time of some chunk of code in Jupyter.  [Image can be found here.](https://sun1-23.userapi.com/c206816/v206816734/171ee6/JWuUUGCfS3M.jpg) I tried to access \"root_MSE\" variable, but no luck :c",
    "performed_via_github_app": null
  }
]
