[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/351815797",
    "html_url": "https://github.com/jupyter/notebook/issues/3131#issuecomment-351815797",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3131",
    "id": 351815797,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM1MTgxNTc5Nw==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-12-14T19:44:20Z",
    "updated_at": "2017-12-14T19:44:20Z",
    "author_association": "MEMBER",
    "body": "That looks like matplotlib is not installed in the environment. From an Anaconda command prompt, activate the Tensorflow environment and then `conda install matplotlib`.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/554278813",
    "html_url": "https://github.com/jupyter/notebook/issues/3131#issuecomment-554278813",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3131",
    "id": 554278813,
    "node_id": "MDEyOklzc3VlQ29tbWVudDU1NDI3ODgxMw==",
    "user": {
      "login": "LobarBadalova",
      "id": 23381595,
      "node_id": "MDQ6VXNlcjIzMzgxNTk1",
      "avatar_url": "https://avatars.githubusercontent.com/u/23381595?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/LobarBadalova",
      "html_url": "https://github.com/LobarBadalova",
      "followers_url": "https://api.github.com/users/LobarBadalova/followers",
      "following_url": "https://api.github.com/users/LobarBadalova/following{/other_user}",
      "gists_url": "https://api.github.com/users/LobarBadalova/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/LobarBadalova/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/LobarBadalova/subscriptions",
      "organizations_url": "https://api.github.com/users/LobarBadalova/orgs",
      "repos_url": "https://api.github.com/users/LobarBadalova/repos",
      "events_url": "https://api.github.com/users/LobarBadalova/events{/privacy}",
      "received_events_url": "https://api.github.com/users/LobarBadalova/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-11-15T09:17:15Z",
    "updated_at": "2019-11-15T09:17:15Z",
    "author_association": "NONE",
    "body": "In cmd , I ran this command \"python -m pip install -U matplotlib\". This solved my problem.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/622011636",
    "html_url": "https://github.com/jupyter/notebook/issues/3131#issuecomment-622011636",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3131",
    "id": 622011636,
    "node_id": "MDEyOklzc3VlQ29tbWVudDYyMjAxMTYzNg==",
    "user": {
      "login": "ZvonimirBandic",
      "id": 1168675,
      "node_id": "MDQ6VXNlcjExNjg2NzU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1168675?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ZvonimirBandic",
      "html_url": "https://github.com/ZvonimirBandic",
      "followers_url": "https://api.github.com/users/ZvonimirBandic/followers",
      "following_url": "https://api.github.com/users/ZvonimirBandic/following{/other_user}",
      "gists_url": "https://api.github.com/users/ZvonimirBandic/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ZvonimirBandic/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ZvonimirBandic/subscriptions",
      "organizations_url": "https://api.github.com/users/ZvonimirBandic/orgs",
      "repos_url": "https://api.github.com/users/ZvonimirBandic/repos",
      "events_url": "https://api.github.com/users/ZvonimirBandic/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ZvonimirBandic/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-04-30T18:01:42Z",
    "updated_at": "2020-04-30T18:01:42Z",
    "author_association": "NONE",
    "body": "Thanks, the re-install solved my similar problem with matplotlib on Windows 10. There is probably a smarter way to re-install, but this I think happened because I installed MikTex after matplotlib, and figuring out $PATH on Windows is non-trival.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/644741101",
    "html_url": "https://github.com/jupyter/notebook/issues/3131#issuecomment-644741101",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3131",
    "id": 644741101,
    "node_id": "MDEyOklzc3VlQ29tbWVudDY0NDc0MTEwMQ==",
    "user": {
      "login": "Ramunaidu812",
      "id": 45794418,
      "node_id": "MDQ6VXNlcjQ1Nzk0NDE4",
      "avatar_url": "https://avatars.githubusercontent.com/u/45794418?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Ramunaidu812",
      "html_url": "https://github.com/Ramunaidu812",
      "followers_url": "https://api.github.com/users/Ramunaidu812/followers",
      "following_url": "https://api.github.com/users/Ramunaidu812/following{/other_user}",
      "gists_url": "https://api.github.com/users/Ramunaidu812/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Ramunaidu812/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Ramunaidu812/subscriptions",
      "organizations_url": "https://api.github.com/users/Ramunaidu812/orgs",
      "repos_url": "https://api.github.com/users/Ramunaidu812/repos",
      "events_url": "https://api.github.com/users/Ramunaidu812/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Ramunaidu812/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-06-16T12:49:02Z",
    "updated_at": "2020-06-16T12:49:02Z",
    "author_association": "NONE",
    "body": "import matplotlib.pyplot as plt\r\n\r\n#handwritten digit recognition\r\nimport numpy as np\r\nimport pandas as pd\r\nimport matplotlib.pyplot as plt\r\n%matplotlib inline\r\nfrom keras.datasets import mnist\r\nfrom keras.models import load_model\r\nfrom keras.utils import to_categorical\r\nUsing TensorFlow backend.\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/682379322",
    "html_url": "https://github.com/jupyter/notebook/issues/3131#issuecomment-682379322",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3131",
    "id": 682379322,
    "node_id": "MDEyOklzc3VlQ29tbWVudDY4MjM3OTMyMg==",
    "user": {
      "login": "Arun-singh-negi",
      "id": 70006540,
      "node_id": "MDQ6VXNlcjcwMDA2NTQw",
      "avatar_url": "https://avatars.githubusercontent.com/u/70006540?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Arun-singh-negi",
      "html_url": "https://github.com/Arun-singh-negi",
      "followers_url": "https://api.github.com/users/Arun-singh-negi/followers",
      "following_url": "https://api.github.com/users/Arun-singh-negi/following{/other_user}",
      "gists_url": "https://api.github.com/users/Arun-singh-negi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Arun-singh-negi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Arun-singh-negi/subscriptions",
      "organizations_url": "https://api.github.com/users/Arun-singh-negi/orgs",
      "repos_url": "https://api.github.com/users/Arun-singh-negi/repos",
      "events_url": "https://api.github.com/users/Arun-singh-negi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Arun-singh-negi/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-08-28T07:40:50Z",
    "updated_at": "2020-08-28T07:40:50Z",
    "author_association": "NONE",
    "body": "> In cmd , I ran this command \"python -m pip install -U matplotlib\". This solved my problem.\r\n\r\nthank you so much ",
    "performed_via_github_app": null
  }
]
