[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/330137230",
    "html_url": "https://github.com/jupyter/notebook/issues/2846#issuecomment-330137230",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/2846",
    "id": 330137230,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMzMDEzNzIzMA==",
    "user": {
      "login": "javadr",
      "id": 1178221,
      "node_id": "MDQ6VXNlcjExNzgyMjE=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1178221?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/javadr",
      "html_url": "https://github.com/javadr",
      "followers_url": "https://api.github.com/users/javadr/followers",
      "following_url": "https://api.github.com/users/javadr/following{/other_user}",
      "gists_url": "https://api.github.com/users/javadr/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/javadr/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/javadr/subscriptions",
      "organizations_url": "https://api.github.com/users/javadr/orgs",
      "repos_url": "https://api.github.com/users/javadr/repos",
      "events_url": "https://api.github.com/users/javadr/events{/privacy}",
      "received_events_url": "https://api.github.com/users/javadr/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-09-18T06:25:54Z",
    "updated_at": "2017-09-18T06:25:54Z",
    "author_association": "NONE",
    "body": "It was because of `matplotlib` not jupyter. \r\n\r\nhttps://github.com/matplotlib/matplotlib/pull/8021",
    "performed_via_github_app": null
  }
]
