[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/561593600",
    "html_url": "https://github.com/jupyter/notebook/issues/5101#issuecomment-561593600",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/5101",
    "id": 561593600,
    "node_id": "MDEyOklzc3VlQ29tbWVudDU2MTU5MzYwMA==",
    "user": {
      "login": "jasongrout",
      "id": 192614,
      "node_id": "MDQ6VXNlcjE5MjYxNA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/192614?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jasongrout",
      "html_url": "https://github.com/jasongrout",
      "followers_url": "https://api.github.com/users/jasongrout/followers",
      "following_url": "https://api.github.com/users/jasongrout/following{/other_user}",
      "gists_url": "https://api.github.com/users/jasongrout/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jasongrout/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jasongrout/subscriptions",
      "organizations_url": "https://api.github.com/users/jasongrout/orgs",
      "repos_url": "https://api.github.com/users/jasongrout/repos",
      "events_url": "https://api.github.com/users/jasongrout/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jasongrout/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-12-04T10:57:51Z",
    "updated_at": "2019-12-04T10:57:51Z",
    "author_association": "MEMBER",
    "body": "Did you mean to do `data_path=''` in that second cell?",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/561595308",
    "html_url": "https://github.com/jupyter/notebook/issues/5101#issuecomment-561595308",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/5101",
    "id": 561595308,
    "node_id": "MDEyOklzc3VlQ29tbWVudDU2MTU5NTMwOA==",
    "user": {
      "login": "lukaskroe",
      "id": 58510627,
      "node_id": "MDQ6VXNlcjU4NTEwNjI3",
      "avatar_url": "https://avatars.githubusercontent.com/u/58510627?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lukaskroe",
      "html_url": "https://github.com/lukaskroe",
      "followers_url": "https://api.github.com/users/lukaskroe/followers",
      "following_url": "https://api.github.com/users/lukaskroe/following{/other_user}",
      "gists_url": "https://api.github.com/users/lukaskroe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lukaskroe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lukaskroe/subscriptions",
      "organizations_url": "https://api.github.com/users/lukaskroe/orgs",
      "repos_url": "https://api.github.com/users/lukaskroe/repos",
      "events_url": "https://api.github.com/users/lukaskroe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lukaskroe/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-12-04T11:02:36Z",
    "updated_at": "2019-12-04T11:03:03Z",
    "author_association": "NONE",
    "body": "Yes, I do this to explicitly clear the variable. However, although I removed the data from the disk and I cleared the variable with `data ='' `, it is still saved somewhere. \r\n\r\nI expect to get an error message after clearing the data from the disk since no data should be able to be loaded. Instead I get the previously opened data.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/561596159",
    "html_url": "https://github.com/jupyter/notebook/issues/5101#issuecomment-561596159",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/5101",
    "id": 561596159,
    "node_id": "MDEyOklzc3VlQ29tbWVudDU2MTU5NjE1OQ==",
    "user": {
      "login": "jasongrout",
      "id": 192614,
      "node_id": "MDQ6VXNlcjE5MjYxNA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/192614?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jasongrout",
      "html_url": "https://github.com/jasongrout",
      "followers_url": "https://api.github.com/users/jasongrout/followers",
      "following_url": "https://api.github.com/users/jasongrout/following{/other_user}",
      "gists_url": "https://api.github.com/users/jasongrout/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jasongrout/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jasongrout/subscriptions",
      "organizations_url": "https://api.github.com/users/jasongrout/orgs",
      "repos_url": "https://api.github.com/users/jasongrout/repos",
      "events_url": "https://api.github.com/users/jasongrout/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jasongrout/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-12-04T11:05:02Z",
    "updated_at": "2019-12-04T11:05:02Z",
    "author_association": "MEMBER",
    "body": "You clear `data`, but use `data_path`",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/561598085",
    "html_url": "https://github.com/jupyter/notebook/issues/5101#issuecomment-561598085",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/5101",
    "id": 561598085,
    "node_id": "MDEyOklzc3VlQ29tbWVudDU2MTU5ODA4NQ==",
    "user": {
      "login": "lukaskroe",
      "id": 58510627,
      "node_id": "MDQ6VXNlcjU4NTEwNjI3",
      "avatar_url": "https://avatars.githubusercontent.com/u/58510627?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lukaskroe",
      "html_url": "https://github.com/lukaskroe",
      "followers_url": "https://api.github.com/users/lukaskroe/followers",
      "following_url": "https://api.github.com/users/lukaskroe/following{/other_user}",
      "gists_url": "https://api.github.com/users/lukaskroe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lukaskroe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lukaskroe/subscriptions",
      "organizations_url": "https://api.github.com/users/lukaskroe/orgs",
      "repos_url": "https://api.github.com/users/lukaskroe/repos",
      "events_url": "https://api.github.com/users/lukaskroe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lukaskroe/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-12-04T11:11:05Z",
    "updated_at": "2019-12-04T11:11:05Z",
    "author_association": "NONE",
    "body": "Yes, that is the point. After the first run of the cell, I delete the data with `rm data_path` in some terminal so that at `data_path` no file exists anymore on the disk.\r\nSo I get for \r\n```bash\r\nls: data_path: No such file or directory\r\n```\r\nWhich is correct, since I deleted it before and I expect similar in jupyter. However, the previously loaded data is still loaded there instead of getting an error message.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/561598651",
    "html_url": "https://github.com/jupyter/notebook/issues/5101#issuecomment-561598651",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/5101",
    "id": 561598651,
    "node_id": "MDEyOklzc3VlQ29tbWVudDU2MTU5ODY1MQ==",
    "user": {
      "login": "lukaskroe",
      "id": 58510627,
      "node_id": "MDQ6VXNlcjU4NTEwNjI3",
      "avatar_url": "https://avatars.githubusercontent.com/u/58510627?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lukaskroe",
      "html_url": "https://github.com/lukaskroe",
      "followers_url": "https://api.github.com/users/lukaskroe/followers",
      "following_url": "https://api.github.com/users/lukaskroe/following{/other_user}",
      "gists_url": "https://api.github.com/users/lukaskroe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lukaskroe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lukaskroe/subscriptions",
      "organizations_url": "https://api.github.com/users/lukaskroe/orgs",
      "repos_url": "https://api.github.com/users/lukaskroe/repos",
      "events_url": "https://api.github.com/users/lukaskroe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lukaskroe/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-12-04T11:12:43Z",
    "updated_at": "2019-12-04T11:13:04Z",
    "author_association": "NONE",
    "body": "I get similar behaviour If I change the original nc file. The new version of the nc file is than not loaded and I still get the output of the old version. Deleting the file is just a more drastic example.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/561599384",
    "html_url": "https://github.com/jupyter/notebook/issues/5101#issuecomment-561599384",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/5101",
    "id": 561599384,
    "node_id": "MDEyOklzc3VlQ29tbWVudDU2MTU5OTM4NA==",
    "user": {
      "login": "jasongrout",
      "id": 192614,
      "node_id": "MDQ6VXNlcjE5MjYxNA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/192614?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jasongrout",
      "html_url": "https://github.com/jasongrout",
      "followers_url": "https://api.github.com/users/jasongrout/followers",
      "following_url": "https://api.github.com/users/jasongrout/following{/other_user}",
      "gists_url": "https://api.github.com/users/jasongrout/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jasongrout/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jasongrout/subscriptions",
      "organizations_url": "https://api.github.com/users/jasongrout/orgs",
      "repos_url": "https://api.github.com/users/jasongrout/repos",
      "events_url": "https://api.github.com/users/jasongrout/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jasongrout/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-12-04T11:14:45Z",
    "updated_at": "2019-12-04T11:14:45Z",
    "author_association": "MEMBER",
    "body": "Change `data=''` to `data_path=''` in your second cell",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/561600137",
    "html_url": "https://github.com/jupyter/notebook/issues/5101#issuecomment-561600137",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/5101",
    "id": 561600137,
    "node_id": "MDEyOklzc3VlQ29tbWVudDU2MTYwMDEzNw==",
    "user": {
      "login": "jasongrout",
      "id": 192614,
      "node_id": "MDQ6VXNlcjE5MjYxNA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/192614?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jasongrout",
      "html_url": "https://github.com/jasongrout",
      "followers_url": "https://api.github.com/users/jasongrout/followers",
      "following_url": "https://api.github.com/users/jasongrout/following{/other_user}",
      "gists_url": "https://api.github.com/users/jasongrout/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jasongrout/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jasongrout/subscriptions",
      "organizations_url": "https://api.github.com/users/jasongrout/orgs",
      "repos_url": "https://api.github.com/users/jasongrout/repos",
      "events_url": "https://api.github.com/users/jasongrout/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jasongrout/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-12-04T11:16:55Z",
    "updated_at": "2019-12-04T11:16:55Z",
    "author_association": "MEMBER",
    "body": "Ah, I see I totally misunderstood the issue. Sorry. Yeah, looks like an xarray issue or testing issue, not a Jupyter issue.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/561601238",
    "html_url": "https://github.com/jupyter/notebook/issues/5101#issuecomment-561601238",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/5101",
    "id": 561601238,
    "node_id": "MDEyOklzc3VlQ29tbWVudDU2MTYwMTIzOA==",
    "user": {
      "login": "lukaskroe",
      "id": 58510627,
      "node_id": "MDQ6VXNlcjU4NTEwNjI3",
      "avatar_url": "https://avatars.githubusercontent.com/u/58510627?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lukaskroe",
      "html_url": "https://github.com/lukaskroe",
      "followers_url": "https://api.github.com/users/lukaskroe/followers",
      "following_url": "https://api.github.com/users/lukaskroe/following{/other_user}",
      "gists_url": "https://api.github.com/users/lukaskroe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lukaskroe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lukaskroe/subscriptions",
      "organizations_url": "https://api.github.com/users/lukaskroe/orgs",
      "repos_url": "https://api.github.com/users/lukaskroe/repos",
      "events_url": "https://api.github.com/users/lukaskroe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lukaskroe/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-12-04T11:20:15Z",
    "updated_at": "2019-12-04T11:20:15Z",
    "author_association": "NONE",
    "body": "Ah ok, thank you Jason, than I'll report this issue to xarray. The only point is that I'm not sure it seems to work fine in ipython.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/561604917",
    "html_url": "https://github.com/jupyter/notebook/issues/5101#issuecomment-561604917",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/5101",
    "id": 561604917,
    "node_id": "MDEyOklzc3VlQ29tbWVudDU2MTYwNDkxNw==",
    "user": {
      "login": "jasongrout",
      "id": 192614,
      "node_id": "MDQ6VXNlcjE5MjYxNA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/192614?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jasongrout",
      "html_url": "https://github.com/jasongrout",
      "followers_url": "https://api.github.com/users/jasongrout/followers",
      "following_url": "https://api.github.com/users/jasongrout/following{/other_user}",
      "gists_url": "https://api.github.com/users/jasongrout/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jasongrout/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jasongrout/subscriptions",
      "organizations_url": "https://api.github.com/users/jasongrout/orgs",
      "repos_url": "https://api.github.com/users/jasongrout/repos",
      "events_url": "https://api.github.com/users/jasongrout/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jasongrout/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-12-04T11:32:07Z",
    "updated_at": "2019-12-04T11:32:27Z",
    "author_association": "MEMBER",
    "body": "If I were you, I would first make absolutely *sure* you were changing/deleting the right file in your tests.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/561619790",
    "html_url": "https://github.com/jupyter/notebook/issues/5101#issuecomment-561619790",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/5101",
    "id": 561619790,
    "node_id": "MDEyOklzc3VlQ29tbWVudDU2MTYxOTc5MA==",
    "user": {
      "login": "lukaskroe",
      "id": 58510627,
      "node_id": "MDQ6VXNlcjU4NTEwNjI3",
      "avatar_url": "https://avatars.githubusercontent.com/u/58510627?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lukaskroe",
      "html_url": "https://github.com/lukaskroe",
      "followers_url": "https://api.github.com/users/lukaskroe/followers",
      "following_url": "https://api.github.com/users/lukaskroe/following{/other_user}",
      "gists_url": "https://api.github.com/users/lukaskroe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lukaskroe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lukaskroe/subscriptions",
      "organizations_url": "https://api.github.com/users/lukaskroe/orgs",
      "repos_url": "https://api.github.com/users/lukaskroe/repos",
      "events_url": "https://api.github.com/users/lukaskroe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lukaskroe/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-12-04T12:19:47Z",
    "updated_at": "2019-12-04T12:19:47Z",
    "author_association": "NONE",
    "body": "This, I definitely made sure :).\r\nI also tried to give a more detailed example and reported it to \r\nhttps://github.com/pydata/xarray/issues/3593",
    "performed_via_github_app": null
  }
]
