[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/490897428",
    "html_url": "https://github.com/jupyter/notebook/issues/4582#issuecomment-490897428",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4582",
    "id": 490897428,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ5MDg5NzQyOA==",
    "user": {
      "login": "thoughtsociety",
      "id": 41583205,
      "node_id": "MDQ6VXNlcjQxNTgzMjA1",
      "avatar_url": "https://avatars.githubusercontent.com/u/41583205?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thoughtsociety",
      "html_url": "https://github.com/thoughtsociety",
      "followers_url": "https://api.github.com/users/thoughtsociety/followers",
      "following_url": "https://api.github.com/users/thoughtsociety/following{/other_user}",
      "gists_url": "https://api.github.com/users/thoughtsociety/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thoughtsociety/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thoughtsociety/subscriptions",
      "organizations_url": "https://api.github.com/users/thoughtsociety/orgs",
      "repos_url": "https://api.github.com/users/thoughtsociety/repos",
      "events_url": "https://api.github.com/users/thoughtsociety/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thoughtsociety/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-05-09T13:10:09Z",
    "updated_at": "2019-05-09T13:10:09Z",
    "author_association": "NONE",
    "body": "Gists or not, this happens too frequently.\r\nJust created a new notebook with Google colab and used their intrinsic feature to push it to my github either as a gist or regular file. It gives the 'something went wrong reload' error and I cannot view this on github.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/494829348",
    "html_url": "https://github.com/jupyter/notebook/issues/4582#issuecomment-494829348",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4582",
    "id": 494829348,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ5NDgyOTM0OA==",
    "user": {
      "login": "sickmint79",
      "id": 14862088,
      "node_id": "MDQ6VXNlcjE0ODYyMDg4",
      "avatar_url": "https://avatars.githubusercontent.com/u/14862088?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sickmint79",
      "html_url": "https://github.com/sickmint79",
      "followers_url": "https://api.github.com/users/sickmint79/followers",
      "following_url": "https://api.github.com/users/sickmint79/following{/other_user}",
      "gists_url": "https://api.github.com/users/sickmint79/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sickmint79/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sickmint79/subscriptions",
      "organizations_url": "https://api.github.com/users/sickmint79/orgs",
      "repos_url": "https://api.github.com/users/sickmint79/repos",
      "events_url": "https://api.github.com/users/sickmint79/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sickmint79/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-05-22T14:33:24Z",
    "updated_at": "2019-05-22T14:33:24Z",
    "author_association": "NONE",
    "body": "bump.  i can see some other people's, public, notebooks; rendering as expected.\r\n\r\nmy own private ones are doing so poorly; not rendering with the same common error above.  they seemed to do so spottily in the past, with no change on my end, sometimes working and sometimes not.  \r\n\r\ni don't really understand why others are working fine, and mine are not.  they are not complex code or anything either.  i have no idea what a workaround might be if one exists.  this makes it much more painful to share/demo example code.  please advise.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/494837081",
    "html_url": "https://github.com/jupyter/notebook/issues/4582#issuecomment-494837081",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4582",
    "id": 494837081,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ5NDgzNzA4MQ==",
    "user": {
      "login": "fhuthmacher",
      "id": 4296824,
      "node_id": "MDQ6VXNlcjQyOTY4MjQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4296824?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fhuthmacher",
      "html_url": "https://github.com/fhuthmacher",
      "followers_url": "https://api.github.com/users/fhuthmacher/followers",
      "following_url": "https://api.github.com/users/fhuthmacher/following{/other_user}",
      "gists_url": "https://api.github.com/users/fhuthmacher/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fhuthmacher/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fhuthmacher/subscriptions",
      "organizations_url": "https://api.github.com/users/fhuthmacher/orgs",
      "repos_url": "https://api.github.com/users/fhuthmacher/repos",
      "events_url": "https://api.github.com/users/fhuthmacher/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fhuthmacher/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-05-22T14:51:21Z",
    "updated_at": "2019-05-22T14:51:21Z",
    "author_association": "NONE",
    "body": "yeah this happens like 90% of the time. Is there any way to change the load time or maybe get a static version of it first?",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/511537786",
    "html_url": "https://github.com/jupyter/notebook/issues/4582#issuecomment-511537786",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4582",
    "id": 511537786,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUxMTUzNzc4Ng==",
    "user": {
      "login": "parrt",
      "id": 178777,
      "node_id": "MDQ6VXNlcjE3ODc3Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/178777?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/parrt",
      "html_url": "https://github.com/parrt",
      "followers_url": "https://api.github.com/users/parrt/followers",
      "following_url": "https://api.github.com/users/parrt/following{/other_user}",
      "gists_url": "https://api.github.com/users/parrt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/parrt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/parrt/subscriptions",
      "organizations_url": "https://api.github.com/users/parrt/orgs",
      "repos_url": "https://api.github.com/users/parrt/repos",
      "events_url": "https://api.github.com/users/parrt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/parrt/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-07-15T19:30:12Z",
    "updated_at": "2019-07-15T19:30:12Z",
    "author_association": "NONE",
    "body": "This is likely github's issue but maybe the jupyter folks can push on them?",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/517294022",
    "html_url": "https://github.com/jupyter/notebook/issues/4582#issuecomment-517294022",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4582",
    "id": 517294022,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUxNzI5NDAyMg==",
    "user": {
      "login": "jasongrout",
      "id": 192614,
      "node_id": "MDQ6VXNlcjE5MjYxNA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/192614?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jasongrout",
      "html_url": "https://github.com/jasongrout",
      "followers_url": "https://api.github.com/users/jasongrout/followers",
      "following_url": "https://api.github.com/users/jasongrout/following{/other_user}",
      "gists_url": "https://api.github.com/users/jasongrout/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jasongrout/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jasongrout/subscriptions",
      "organizations_url": "https://api.github.com/users/jasongrout/orgs",
      "repos_url": "https://api.github.com/users/jasongrout/repos",
      "events_url": "https://api.github.com/users/jasongrout/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jasongrout/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-08-01T13:43:47Z",
    "updated_at": "2019-08-01T13:43:47Z",
    "author_association": "MEMBER",
    "body": "Please file a support request to GitHub: https://github.com/contact\r\n\r\nWe have no control over how GitHub renders notebooks. I don't know if they even see these issues raised here. It's much more productive to file the support request to GitHub so they can be aware of the issue and hopefully fix it.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/517294359",
    "html_url": "https://github.com/jupyter/notebook/issues/4582#issuecomment-517294359",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4582",
    "id": 517294359,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUxNzI5NDM1OQ==",
    "user": {
      "login": "jasongrout",
      "id": 192614,
      "node_id": "MDQ6VXNlcjE5MjYxNA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/192614?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jasongrout",
      "html_url": "https://github.com/jasongrout",
      "followers_url": "https://api.github.com/users/jasongrout/followers",
      "following_url": "https://api.github.com/users/jasongrout/following{/other_user}",
      "gists_url": "https://api.github.com/users/jasongrout/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jasongrout/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jasongrout/subscriptions",
      "organizations_url": "https://api.github.com/users/jasongrout/orgs",
      "repos_url": "https://api.github.com/users/jasongrout/repos",
      "events_url": "https://api.github.com/users/jasongrout/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jasongrout/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-08-01T13:44:33Z",
    "updated_at": "2019-08-01T13:44:33Z",
    "author_association": "MEMBER",
    "body": "c.f. #3555 and #3035",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/641442047",
    "html_url": "https://github.com/jupyter/notebook/issues/4582#issuecomment-641442047",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4582",
    "id": 641442047,
    "node_id": "MDEyOklzc3VlQ29tbWVudDY0MTQ0MjA0Nw==",
    "user": {
      "login": "DanielGoldfarb",
      "id": 11164790,
      "node_id": "MDQ6VXNlcjExMTY0Nzkw",
      "avatar_url": "https://avatars.githubusercontent.com/u/11164790?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/DanielGoldfarb",
      "html_url": "https://github.com/DanielGoldfarb",
      "followers_url": "https://api.github.com/users/DanielGoldfarb/followers",
      "following_url": "https://api.github.com/users/DanielGoldfarb/following{/other_user}",
      "gists_url": "https://api.github.com/users/DanielGoldfarb/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/DanielGoldfarb/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/DanielGoldfarb/subscriptions",
      "organizations_url": "https://api.github.com/users/DanielGoldfarb/orgs",
      "repos_url": "https://api.github.com/users/DanielGoldfarb/repos",
      "events_url": "https://api.github.com/users/DanielGoldfarb/events{/privacy}",
      "received_events_url": "https://api.github.com/users/DanielGoldfarb/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-06-09T16:55:09Z",
    "updated_at": "2020-06-09T16:56:46Z",
    "author_association": "NONE",
    "body": "**To anyone reading this** ***who works for github.com, or who knows someone who works for github.com:***\r\n\r\nI have been grappling with the `Sorry, something went wrong. [Reload?]` issue for months. I have many notebooks in many repositories. ([One such example is here](https://github.com/matplotlib/mplfinance/tree/master/examples)).\r\n\r\nWhenever the notebooks fail with `Sorry, something went wrong. [Reload?]`, _the same notebook will be fine some time later_, where “_some time later_” can be anywhere from several minutes to several hours (up to maybe a day). However that doesn’t mean that it won’t start failing again several hours after that!\r\n\r\n**I am convinced this is a github.com issue**, and that github.com is using a service (hosted somewhere) to render notebooks, and that sometimes this service either gets into a bad state, or crashes; when that happens notebooks won’t render until the service is bounced, or somehow has its “good” state restored.  \r\n\r\n(possibly this could also be a network issue in just reaching the service to render notebooks, but based on my observations i am more convinced of the \"bad\" state service hypothesis).\r\n\r\nI would be happy to volunteer my time to help investigate the issue, if it is otherwise not a priority for github.com to allocate the resources. Please let me know if there is anything I can do to help.\r\n\r\n**Please note:** This can be very inconvenient, even embarrassing, to say the least, when I am trying to provide support to users of my public repositories and they tell me that the notebooks to which I direct them are not rendering.\r\n\r\nThank you.\r\nP.S.  I have tried reporting this issue to github.com support but, so far, no response.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/641458969",
    "html_url": "https://github.com/jupyter/notebook/issues/4582#issuecomment-641458969",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4582",
    "id": 641458969,
    "node_id": "MDEyOklzc3VlQ29tbWVudDY0MTQ1ODk2OQ==",
    "user": {
      "login": "parrt",
      "id": 178777,
      "node_id": "MDQ6VXNlcjE3ODc3Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/178777?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/parrt",
      "html_url": "https://github.com/parrt",
      "followers_url": "https://api.github.com/users/parrt/followers",
      "following_url": "https://api.github.com/users/parrt/following{/other_user}",
      "gists_url": "https://api.github.com/users/parrt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/parrt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/parrt/subscriptions",
      "organizations_url": "https://api.github.com/users/parrt/orgs",
      "repos_url": "https://api.github.com/users/parrt/repos",
      "events_url": "https://api.github.com/users/parrt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/parrt/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-06-09T17:20:29Z",
    "updated_at": "2020-06-09T17:20:29Z",
    "author_association": "NONE",
    "body": "Agreed. It's absurd how often github fails to render.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/641530513",
    "html_url": "https://github.com/jupyter/notebook/issues/4582#issuecomment-641530513",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4582",
    "id": 641530513,
    "node_id": "MDEyOklzc3VlQ29tbWVudDY0MTUzMDUxMw==",
    "user": {
      "login": "DanielGoldfarb",
      "id": 11164790,
      "node_id": "MDQ6VXNlcjExMTY0Nzkw",
      "avatar_url": "https://avatars.githubusercontent.com/u/11164790?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/DanielGoldfarb",
      "html_url": "https://github.com/DanielGoldfarb",
      "followers_url": "https://api.github.com/users/DanielGoldfarb/followers",
      "following_url": "https://api.github.com/users/DanielGoldfarb/following{/other_user}",
      "gists_url": "https://api.github.com/users/DanielGoldfarb/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/DanielGoldfarb/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/DanielGoldfarb/subscriptions",
      "organizations_url": "https://api.github.com/users/DanielGoldfarb/orgs",
      "repos_url": "https://api.github.com/users/DanielGoldfarb/repos",
      "events_url": "https://api.github.com/users/DanielGoldfarb/events{/privacy}",
      "received_events_url": "https://api.github.com/users/DanielGoldfarb/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-06-09T19:43:18Z",
    "updated_at": "2020-06-09T19:43:18Z",
    "author_association": "NONE",
    "body": "@parrt \r\nTerence,\r\n  Perhaps we can organize a grass roots effort to have a lot of people request, through https://support.github.com/contact , that this issue be fixed?\r\n   --Daniel",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/641531090",
    "html_url": "https://github.com/jupyter/notebook/issues/4582#issuecomment-641531090",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4582",
    "id": 641531090,
    "node_id": "MDEyOklzc3VlQ29tbWVudDY0MTUzMTA5MA==",
    "user": {
      "login": "parrt",
      "id": 178777,
      "node_id": "MDQ6VXNlcjE3ODc3Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/178777?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/parrt",
      "html_url": "https://github.com/parrt",
      "followers_url": "https://api.github.com/users/parrt/followers",
      "following_url": "https://api.github.com/users/parrt/following{/other_user}",
      "gists_url": "https://api.github.com/users/parrt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/parrt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/parrt/subscriptions",
      "organizations_url": "https://api.github.com/users/parrt/orgs",
      "repos_url": "https://api.github.com/users/parrt/repos",
      "events_url": "https://api.github.com/users/parrt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/parrt/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-06-09T19:44:38Z",
    "updated_at": "2020-06-09T19:44:38Z",
    "author_association": "NONE",
    "body": "hiya @DanielGoldfarb. The CEO at github knows and promised improvements (saw on twitter) but that was a while ago.   I'm really curious what the issue is.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/658094926",
    "html_url": "https://github.com/jupyter/notebook/issues/4582#issuecomment-658094926",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4582",
    "id": 658094926,
    "node_id": "MDEyOklzc3VlQ29tbWVudDY1ODA5NDkyNg==",
    "user": {
      "login": "qemtek",
      "id": 18211372,
      "node_id": "MDQ6VXNlcjE4MjExMzcy",
      "avatar_url": "https://avatars.githubusercontent.com/u/18211372?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/qemtek",
      "html_url": "https://github.com/qemtek",
      "followers_url": "https://api.github.com/users/qemtek/followers",
      "following_url": "https://api.github.com/users/qemtek/following{/other_user}",
      "gists_url": "https://api.github.com/users/qemtek/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/qemtek/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/qemtek/subscriptions",
      "organizations_url": "https://api.github.com/users/qemtek/orgs",
      "repos_url": "https://api.github.com/users/qemtek/repos",
      "events_url": "https://api.github.com/users/qemtek/events{/privacy}",
      "received_events_url": "https://api.github.com/users/qemtek/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-07-14T10:09:03Z",
    "updated_at": "2020-07-14T10:09:03Z",
    "author_association": "NONE",
    "body": "This is a huge downside of GitHub. I'm trying to follow Amazon's guides to develop on SageMaker and every example points to a jupyter notebook hosted on GitHub... ",
    "performed_via_github_app": null
  }
]
