[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/340746249",
    "html_url": "https://github.com/jupyter/notebook/issues/2956#issuecomment-340746249",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/2956",
    "id": 340746249,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM0MDc0NjI0OQ==",
    "user": {
      "login": "Carleslc",
      "id": 8451756,
      "node_id": "MDQ6VXNlcjg0NTE3NTY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8451756?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Carleslc",
      "html_url": "https://github.com/Carleslc",
      "followers_url": "https://api.github.com/users/Carleslc/followers",
      "following_url": "https://api.github.com/users/Carleslc/following{/other_user}",
      "gists_url": "https://api.github.com/users/Carleslc/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Carleslc/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Carleslc/subscriptions",
      "organizations_url": "https://api.github.com/users/Carleslc/orgs",
      "repos_url": "https://api.github.com/users/Carleslc/repos",
      "events_url": "https://api.github.com/users/Carleslc/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Carleslc/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-10-31T12:24:04Z",
    "updated_at": "2017-10-31T12:25:14Z",
    "author_association": "NONE",
    "body": "Having the same error here when trying to execute Jupyter notebook from anaconda navigator and MacOS High Sierra.\r\n\r\n`conda info` reports:\r\n\r\n```\r\nCurrent conda install:\r\n\r\n               platform : osx-64\r\n          conda version : 4.3.30\r\n       conda is private : False\r\n      conda-env version : 4.3.30\r\n    conda-build version : not installed\r\n         python version : 3.6.1.final.0\r\n       requests version : 2.14.2\r\n       root environment : /anaconda  (writable)\r\n    default environment : /anaconda\r\n       envs directories : /anaconda/envs\r\n                          /Users/carleslc/.conda/envs\r\n          package cache : /anaconda/pkgs\r\n                          /Users/carleslc/.conda/pkgs\r\n           channel URLs : https://repo.continuum.io/pkgs/main/osx-64\r\n                          https://repo.continuum.io/pkgs/main/noarch\r\n                          https://repo.continuum.io/pkgs/free/osx-64\r\n                          https://repo.continuum.io/pkgs/free/noarch\r\n                          https://repo.continuum.io/pkgs/r/osx-64\r\n                          https://repo.continuum.io/pkgs/r/noarch\r\n                          https://repo.continuum.io/pkgs/pro/osx-64\r\n                          https://repo.continuum.io/pkgs/pro/noarch\r\n            config file : /Users/carleslc/.condarc\r\n             netrc file : None\r\n           offline mode : False\r\n             user-agent : conda/4.3.30 requests/2.14.2 CPython/3.6.1 Darwin/17.0.0 OSX/10.13    \r\n                UID:GID : 501:20\r\n```\r\n\r\n`jupyter notebook` works fine when it is executed in terminal.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/475868393",
    "html_url": "https://github.com/jupyter/notebook/issues/2956#issuecomment-475868393",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/2956",
    "id": 475868393,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3NTg2ODM5Mw==",
    "user": {
      "login": "WinsleyJ",
      "id": 20803684,
      "node_id": "MDQ6VXNlcjIwODAzNjg0",
      "avatar_url": "https://avatars.githubusercontent.com/u/20803684?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/WinsleyJ",
      "html_url": "https://github.com/WinsleyJ",
      "followers_url": "https://api.github.com/users/WinsleyJ/followers",
      "following_url": "https://api.github.com/users/WinsleyJ/following{/other_user}",
      "gists_url": "https://api.github.com/users/WinsleyJ/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/WinsleyJ/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/WinsleyJ/subscriptions",
      "organizations_url": "https://api.github.com/users/WinsleyJ/orgs",
      "repos_url": "https://api.github.com/users/WinsleyJ/repos",
      "events_url": "https://api.github.com/users/WinsleyJ/events{/privacy}",
      "received_events_url": "https://api.github.com/users/WinsleyJ/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-03-23T13:08:00Z",
    "updated_at": "2019-03-23T13:08:00Z",
    "author_association": "NONE",
    "body": "I'm having the same error when launching from anaconda navigator. Please help me out.\r\n\r\n`~/Desktop /anaconda3/bin/jupyter_mac.command ; exit;\r\nFailed to execute process '/anaconda3/bin/jupyter_mac.command'. Reason:\r\nexec: Exec format error\r\nThe file '/anaconda3/bin/jupyter_mac.command' is marked as an executable but could not be run by the operating system.     `",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/544202233",
    "html_url": "https://github.com/jupyter/notebook/issues/2956#issuecomment-544202233",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/2956",
    "id": 544202233,
    "node_id": "MDEyOklzc3VlQ29tbWVudDU0NDIwMjIzMw==",
    "user": {
      "login": "dkk",
      "id": 576723,
      "node_id": "MDQ6VXNlcjU3NjcyMw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/576723?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dkk",
      "html_url": "https://github.com/dkk",
      "followers_url": "https://api.github.com/users/dkk/followers",
      "following_url": "https://api.github.com/users/dkk/following{/other_user}",
      "gists_url": "https://api.github.com/users/dkk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dkk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dkk/subscriptions",
      "organizations_url": "https://api.github.com/users/dkk/orgs",
      "repos_url": "https://api.github.com/users/dkk/repos",
      "events_url": "https://api.github.com/users/dkk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dkk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-10-19T22:24:53Z",
    "updated_at": "2019-10-19T22:24:53Z",
    "author_association": "NONE",
    "body": "I also get the error\r\n```\r\nFailed to execute process 'XXX/anaconda3/bin/jupyter_mac.command'. Reason:\r\nexec: Exec format error\r\nThe file 'XXX/anaconda3/bin/jupyter_mac.command' is marked as an executable but could not be run by the operating system.\r\n```\r\nwhen trying to launch jupyter-notebooks from the anaconda navigator.\r\n\r\nconda info shows:\r\n\r\n```\r\n     active environment : base\r\n    active env location : XXX/anaconda3\r\n            shell level : 1\r\n       user config file : XXX/../../.condarc\r\n populated config files : XXX/../../.condarc\r\n          conda version : 4.7.12\r\n    conda-build version : 3.18.9\r\n         python version : 3.7.4.final.0\r\n       virtual packages : \r\n       base environment : XXX/anaconda3  (writable)\r\n           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64\r\n                          https://repo.anaconda.com/pkgs/main/noarch\r\n                          https://repo.anaconda.com/pkgs/r/osx-64\r\n                          https://repo.anaconda.com/pkgs/r/noarch\r\n          package cache : XXX/anaconda3/pkgs\r\n                          XXX/../../.conda/pkgs\r\n       envs directories : XXX/anaconda3/envs\r\n                          XXX/../../.conda/envs\r\n               platform : osx-64\r\n             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Darwin/18.7.0 OSX/10.14.6\r\n                UID:GID : 501:20\r\n             netrc file : None\r\n           offline mode : False\r\n```\r\n\r\n",
    "performed_via_github_app": null
  }
]
