[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/145299087",
    "html_url": "https://github.com/jupyter/notebook/issues/522#issuecomment-145299087",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/522",
    "id": 145299087,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NTI5OTA4Nw==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-03T23:31:36Z",
    "updated_at": "2015-10-03T23:31:36Z",
    "author_association": "MEMBER",
    "body": "It's showing 200 OK for me. Are you sure your Python 3 is running master?\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/145608616",
    "html_url": "https://github.com/jupyter/notebook/issues/522#issuecomment-145608616",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/522",
    "id": 145608616,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NTYwODYxNg==",
    "user": {
      "login": "zischwartz",
      "id": 77472,
      "node_id": "MDQ6VXNlcjc3NDcy",
      "avatar_url": "https://avatars.githubusercontent.com/u/77472?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zischwartz",
      "html_url": "https://github.com/zischwartz",
      "followers_url": "https://api.github.com/users/zischwartz/followers",
      "following_url": "https://api.github.com/users/zischwartz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zischwartz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zischwartz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zischwartz/subscriptions",
      "organizations_url": "https://api.github.com/users/zischwartz/orgs",
      "repos_url": "https://api.github.com/users/zischwartz/repos",
      "events_url": "https://api.github.com/users/zischwartz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zischwartz/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-05T17:38:11Z",
    "updated_at": "2015-10-05T17:38:11Z",
    "author_association": "CONTRIBUTOR",
    "body": "I think I've figured it out, at least partially.\n\nBuilding from master in this repo, everything works. The problem occurs when I also install [ipywidgets](https://github.com/ipython/ipywidgets). Then I get the 405 on the OPTIONS preflight to the kernel endpoint, as seen here.\n\n![screen shot 2015-10-05 at 1 03 31 pm](https://cloud.githubusercontent.com/assets/77472/10288340/4e8f231e-6b66-11e5-9cdc-ccb53a38e533.png)\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/145619557",
    "html_url": "https://github.com/jupyter/notebook/issues/522#issuecomment-145619557",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/522",
    "id": 145619557,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NTYxOTU1Nw==",
    "user": {
      "login": "zischwartz",
      "id": 77472,
      "node_id": "MDQ6VXNlcjc3NDcy",
      "avatar_url": "https://avatars.githubusercontent.com/u/77472?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zischwartz",
      "html_url": "https://github.com/zischwartz",
      "followers_url": "https://api.github.com/users/zischwartz/followers",
      "following_url": "https://api.github.com/users/zischwartz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zischwartz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zischwartz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zischwartz/subscriptions",
      "organizations_url": "https://api.github.com/users/zischwartz/orgs",
      "repos_url": "https://api.github.com/users/zischwartz/repos",
      "events_url": "https://api.github.com/users/zischwartz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zischwartz/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-05T18:12:17Z",
    "updated_at": "2015-10-05T18:12:26Z",
    "author_association": "CONTRIBUTOR",
    "body": "Aha! Using the `--no-deps` option when pip installing ipywidgets, doesn't cause this issue.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/145627271",
    "html_url": "https://github.com/jupyter/notebook/issues/522#issuecomment-145627271",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/522",
    "id": 145627271,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NTYyNzI3MQ==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-05T18:42:34Z",
    "updated_at": "2015-10-05T18:42:34Z",
    "author_association": "MEMBER",
    "body": "What do you have for `pip list` after installing the widgets?\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/145630621",
    "html_url": "https://github.com/jupyter/notebook/issues/522#issuecomment-145630621",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/522",
    "id": 145630621,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NTYzMDYyMQ==",
    "user": {
      "login": "zischwartz",
      "id": 77472,
      "node_id": "MDQ6VXNlcjc3NDcy",
      "avatar_url": "https://avatars.githubusercontent.com/u/77472?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zischwartz",
      "html_url": "https://github.com/zischwartz",
      "followers_url": "https://api.github.com/users/zischwartz/followers",
      "following_url": "https://api.github.com/users/zischwartz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zischwartz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zischwartz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zischwartz/subscriptions",
      "organizations_url": "https://api.github.com/users/zischwartz/orgs",
      "repos_url": "https://api.github.com/users/zischwartz/repos",
      "events_url": "https://api.github.com/users/zischwartz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zischwartz/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-05T18:52:30Z",
    "updated_at": "2015-10-05T18:52:30Z",
    "author_association": "CONTRIBUTOR",
    "body": "After installing **with** `--no-deps`\n\n```\nroot@ecd6c216754b:/srv/notebook# pip list\nchardet (2.0.1)\ncolorama (0.2.5)\ndecorator (4.0.4)\ndocutils (0.11)\ngyp (0.1)\nhtml5lib (0.999)\nipykernel (4.0.3)\nipython (4.0.0)\nipython-genutils (0.1.0)\nipywidgets (4.0.3)\nJinja2 (2.7.2)\njupyter-client (4.0.0)\njupyter-core (4.0.6)\nMarkupSafe (0.18)\npath.py (8.1.1)\npexpect (3.3)\npickleshare (0.5)\nPillow (2.3.0)\npip (7.1.2)\nPygments (1.6)\npyzmq (14.7.0)\nrequests (2.2.1)\nroman (2.0.0)\nsetuptools (18.3.2)\nsimplegeneric (0.8.1)\nsix (1.5.2)\nSphinx (1.2.2)\ntraitlets (4.0.0)\nurllib3 (1.7.1)\nwheel (0.24.0)\n```\n\nAfter installing the widgets **without** `--no-deps`:\n\n```\nbackports.ssl-match-hostname (3.4.0.2)\ncertifi (2015.9.6.2)\nchardet (2.0.1)\ncolorama (0.2.5)\ndecorator (4.0.4)\ndocutils (0.11)\nfunctools32 (3.2.3.post2)\ngyp (0.1)\nhtml5lib (0.999)\nipykernel (4.0.3)\nipython (4.0.0)\nipython-genutils (0.1.0)\nipywidgets (4.0.3)\nJinja2 (2.7.2)\njsonschema (2.5.1)\njupyter-client (4.0.0)\njupyter-core (4.0.6)\nMarkupSafe (0.18)\nmistune (0.7.1)\nnbconvert (4.0.0)\nnbformat (4.0.1)\nnotebook (4.0.5)\npath.py (8.1.1)\npexpect (3.3)\npickleshare (0.5)\nPillow (2.3.0)\npip (7.1.2)\nptyprocess (0.5)\nPygments (1.6)\npyzmq (14.7.0)\nrequests (2.2.1)\nroman (2.0.0)\nsetuptools (18.3.2)\nsimplegeneric (0.8.1)\nsix (1.5.2)\nSphinx (1.2.2)\nterminado (0.5)\ntornado (4.2.1)\ntraitlets (4.0.0)\nurllib3 (1.7.1)\nwheel (0.24.0)\n```\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/145673009",
    "html_url": "https://github.com/jupyter/notebook/issues/522#issuecomment-145673009",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/522",
    "id": 145673009,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NTY3MzAwOQ==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-05T21:25:35Z",
    "updated_at": "2015-10-05T21:25:35Z",
    "author_association": "MEMBER",
    "body": "I'm not sure how it's working when you use `--no-deps`, since it shows that you don't have the notebook package at all. When you install with dependencies, you do have the notebook and it is 4.0.5, which is current stable and doesn't have the fix referred to here. Perhaps you have notebook master installed in a different env?\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/145676673",
    "html_url": "https://github.com/jupyter/notebook/issues/522#issuecomment-145676673",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/522",
    "id": 145676673,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NTY3NjY3Mw==",
    "user": {
      "login": "zischwartz",
      "id": 77472,
      "node_id": "MDQ6VXNlcjc3NDcy",
      "avatar_url": "https://avatars.githubusercontent.com/u/77472?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zischwartz",
      "html_url": "https://github.com/zischwartz",
      "followers_url": "https://api.github.com/users/zischwartz/followers",
      "following_url": "https://api.github.com/users/zischwartz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zischwartz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zischwartz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zischwartz/subscriptions",
      "organizations_url": "https://api.github.com/users/zischwartz/orgs",
      "repos_url": "https://api.github.com/users/zischwartz/repos",
      "events_url": "https://api.github.com/users/zischwartz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zischwartz/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-05T21:42:17Z",
    "updated_at": "2015-10-05T21:42:17Z",
    "author_association": "CONTRIBUTOR",
    "body": "Well I think the notebook is being installed by [this line in the Dockerfile](https://github.com/jupyter/notebook/blob/master/Dockerfile#L54):\n\n```\nRUN pip3 install --pre -e .\n```\n\nWhich I guess doesn't make it into `pip list`. \n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/145781397",
    "html_url": "https://github.com/jupyter/notebook/issues/522#issuecomment-145781397",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/522",
    "id": 145781397,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NTc4MTM5Nw==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-06T08:26:49Z",
    "updated_at": "2015-10-06T08:26:54Z",
    "author_association": "MEMBER",
    "body": "@zischwartz `pip install -e` will indeed show up in `pip list`. Do you have your own Dockerfile that's exhibiting this problem?\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/145801570",
    "html_url": "https://github.com/jupyter/notebook/issues/522#issuecomment-145801570",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/522",
    "id": 145801570,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NTgwMTU3MA==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-06T09:47:19Z",
    "updated_at": "2015-10-06T09:47:19Z",
    "author_association": "MEMBER",
    "body": "I just realized: if you are using that Dockerfile, `pip` is `pip2`, and the notebook is only installed with pip3. What do you see for `pip3 list`?\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/145838353",
    "html_url": "https://github.com/jupyter/notebook/issues/522#issuecomment-145838353",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/522",
    "id": 145838353,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NTgzODM1Mw==",
    "user": {
      "login": "jdfreder",
      "id": 3292874,
      "node_id": "MDQ6VXNlcjMyOTI4NzQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3292874?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jdfreder",
      "html_url": "https://github.com/jdfreder",
      "followers_url": "https://api.github.com/users/jdfreder/followers",
      "following_url": "https://api.github.com/users/jdfreder/following{/other_user}",
      "gists_url": "https://api.github.com/users/jdfreder/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jdfreder/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jdfreder/subscriptions",
      "organizations_url": "https://api.github.com/users/jdfreder/orgs",
      "repos_url": "https://api.github.com/users/jdfreder/repos",
      "events_url": "https://api.github.com/users/jdfreder/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jdfreder/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-06T12:09:52Z",
    "updated_at": "2015-10-06T12:09:52Z",
    "author_association": "CONTRIBUTOR",
    "body": "Aside: I should have mentioned, I opened this issue for @zischwartz when I was visiting last Thur/Fri.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/145840794",
    "html_url": "https://github.com/jupyter/notebook/issues/522#issuecomment-145840794",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/522",
    "id": 145840794,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NTg0MDc5NA==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-06T12:22:58Z",
    "updated_at": "2015-10-06T12:22:58Z",
    "author_association": "MEMBER",
    "body": "Here's what I suspect is happening:\n- jupyter-notebook master is installed with pip3\n- installing ipywidgets with pip installs with Python 2, depends on the notebook, and installs `jupyter-notebook` for Python 2.\n- now `jupyter-notebook` is pointing to the Python 2 version, which is current stable, instead of dev.\n\nIf we were installing Python 2 in an env, instead of the default, this wouldn't be an issue. Similarly, this wouldn't be an issue if the command were `python3 -m notebook` instead of `jupyter notebook`.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/145876271",
    "html_url": "https://github.com/jupyter/notebook/issues/522#issuecomment-145876271",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/522",
    "id": 145876271,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NTg3NjI3MQ==",
    "user": {
      "login": "zischwartz",
      "id": 77472,
      "node_id": "MDQ6VXNlcjc3NDcy",
      "avatar_url": "https://avatars.githubusercontent.com/u/77472?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zischwartz",
      "html_url": "https://github.com/zischwartz",
      "followers_url": "https://api.github.com/users/zischwartz/followers",
      "following_url": "https://api.github.com/users/zischwartz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zischwartz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zischwartz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zischwartz/subscriptions",
      "organizations_url": "https://api.github.com/users/zischwartz/orgs",
      "repos_url": "https://api.github.com/users/zischwartz/repos",
      "events_url": "https://api.github.com/users/zischwartz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zischwartz/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-06T14:37:00Z",
    "updated_at": "2015-10-06T14:38:10Z",
    "author_association": "CONTRIBUTOR",
    "body": "Hmm ok, I was installing the widgets with both `pip2` and `pip3`. And yeah here's my [Dockerfile](https://github.com/zischwartz/notebook/blob/master/Dockerfile#L60-L61).\n\nWith `--no-deps`\n\n```\nroot@edc33e53a4d9:/srv/notebook# pip3 list\nchardet (2.2.1)\ncolorama (0.2.5)\ndecorator (4.0.4)\ndocutils (0.11)\nhtml5lib (0.999)\nipykernel (4.0.3)\nipython (4.0.0)\nipython-genutils (0.1.0)\nipywidgets (4.0.3)\nJinja2 (2.7.2)\njsonschema (2.5.1)\njupyter-client (4.0.0)\njupyter-core (4.0.6)\nMarkupSafe (0.18)\nmistune (0.7.1)\nnbconvert (4.0.0)\nnbformat (4.0.1)\nnotebook (4.1.0.dev0, /srv/notebook)\npath.py (8.1.1)\npexpect (3.3)\npickleshare (0.5)\nPillow (2.3.0)\npip (7.1.2)\nptyprocess (0.5)\nPygments (1.6)\npyzmq (14.7.0)\nrequests (2.2.1)\nroman (2.0.0)\nsetuptools (18.3.2)\nsimplegeneric (0.8.1)\nsix (1.5.2)\nSphinx (1.2.2)\nterminado (0.5)\ntornado (4.2.1)\ntraitlets (4.0.0)\nurllib3 (1.7.1)\nwheel (0.24.0)\n```\n\nWithout `--no-deps`:\n\n```\nroot@fb072da9ecb2:/srv/notebook# pip3 list\nchardet (2.2.1)\ncolorama (0.2.5)\ndecorator (4.0.4)\ndocutils (0.11)\nhtml5lib (0.999)\nipykernel (4.0.3)\nipython (4.0.0)\nipython-genutils (0.1.0)\nipywidgets (4.0.3)\nJinja2 (2.7.2)\njsonschema (2.5.1)\njupyter-client (4.0.0)\njupyter-core (4.0.6)\nMarkupSafe (0.18)\nmistune (0.7.1)\nnbconvert (4.0.0)\nnbformat (4.0.1)\nnotebook (4.1.0.dev0, /srv/notebook)\npath.py (8.1.1)\npexpect (3.3)\npickleshare (0.5)\nPillow (2.3.0)\npip (7.1.2)\nptyprocess (0.5)\nPygments (1.6)\npyzmq (14.7.0)\nrequests (2.2.1)\nroman (2.0.0)\nsetuptools (18.3.2)\nsimplegeneric (0.8.1)\nsix (1.5.2)\nSphinx (1.2.2)\nterminado (0.5)\ntornado (4.2.1)\ntraitlets (4.0.0)\nurllib3 (1.7.1)\nwheel (0.24.0)\n```\n\nSeems identical.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/145928091",
    "html_url": "https://github.com/jupyter/notebook/issues/522#issuecomment-145928091",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/522",
    "id": 145928091,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NTkyODA5MQ==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-06T17:00:51Z",
    "updated_at": "2015-10-06T17:00:51Z",
    "author_association": "MEMBER",
    "body": "Yup, then what I described above is what's happening. Since `ipywidgets` depends on the notebook package, when you install it for Python 2, it's installing `jupyter-notebook` for Python 2, overwriting the version previously installed with Python 3. Python 3 still has the latest version of the notebook, it's just not what's getting launched when `jupyter notebook` is called. If we change the command to be `python3 -m notebook` instead of `jupyter notebook` there would be no problem.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146326424",
    "html_url": "https://github.com/jupyter/notebook/issues/522#issuecomment-146326424",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/522",
    "id": 146326424,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjMyNjQyNA==",
    "user": {
      "login": "ngoldbaum",
      "id": 3126246,
      "node_id": "MDQ6VXNlcjMxMjYyNDY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3126246?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ngoldbaum",
      "html_url": "https://github.com/ngoldbaum",
      "followers_url": "https://api.github.com/users/ngoldbaum/followers",
      "following_url": "https://api.github.com/users/ngoldbaum/following{/other_user}",
      "gists_url": "https://api.github.com/users/ngoldbaum/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ngoldbaum/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ngoldbaum/subscriptions",
      "organizations_url": "https://api.github.com/users/ngoldbaum/orgs",
      "repos_url": "https://api.github.com/users/ngoldbaum/repos",
      "events_url": "https://api.github.com/users/ngoldbaum/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ngoldbaum/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-07T20:58:24Z",
    "updated_at": "2015-10-07T20:58:24Z",
    "author_association": "NONE",
    "body": "I'm getting this using both a python2 and python3 notebook server, trying to run thebe. I set up IPython using a python3 virtualenv on Ubuntu 14.04. In this context pip is always referring to python3's pip.\n\nAny idea how I can work around this?\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146328781",
    "html_url": "https://github.com/jupyter/notebook/issues/522#issuecomment-146328781",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/522",
    "id": 146328781,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjMyODc4MQ==",
    "user": {
      "login": "ngoldbaum",
      "id": 3126246,
      "node_id": "MDQ6VXNlcjMxMjYyNDY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3126246?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ngoldbaum",
      "html_url": "https://github.com/ngoldbaum",
      "followers_url": "https://api.github.com/users/ngoldbaum/followers",
      "following_url": "https://api.github.com/users/ngoldbaum/following{/other_user}",
      "gists_url": "https://api.github.com/users/ngoldbaum/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ngoldbaum/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ngoldbaum/subscriptions",
      "organizations_url": "https://api.github.com/users/ngoldbaum/orgs",
      "repos_url": "https://api.github.com/users/ngoldbaum/repos",
      "events_url": "https://api.github.com/users/ngoldbaum/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ngoldbaum/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-07T21:03:21Z",
    "updated_at": "2015-10-07T21:03:21Z",
    "author_association": "NONE",
    "body": "Here's my `pip list` if it helps:\n\n```\nCython (0.23.3)\ndecorator (4.0.4)\nipykernel (4.1.0)\nipython (4.0.0)\nipython-genutils (0.1.0)\nipywidgets (4.0.3)\nJinja2 (2.8)\njsonschema (2.5.1)\njupyter (1.0.0)\njupyter-client (4.0.0)\njupyter-console (4.0.3)\njupyter-core (4.0.6)\nMarkupSafe (0.23)\nmatplotlib (1.4.3)\nmistune (0.7.1)\nnbconvert (4.0.0)\nnbformat (4.0.1)\nnose (1.3.7)\nnotebook (4.0.5)\nnumpy (1.10.0.post2)\npath.py (8.1.2)\npexpect (4.0.1)\npickleshare (0.5)\npip (7.1.2)\nptyprocess (0.5)\nPygments (2.0.2)\npyparsing (2.0.3)\npython-dateutil (2.4.2)\npytz (2015.6)\npyzmq (14.7.0)\nqtconsole (4.0.1)\nsetuptools (18.2)\nsimplegeneric (0.8.1)\nsix (1.10.0)\nsympy (0.7.6.1)\nterminado (0.5)\ntornado (4.2.1)\ntraitlets (4.0.0)\nwheel (0.24.0)\nyt (3.2.1)\n```\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146560756",
    "html_url": "https://github.com/jupyter/notebook/issues/522#issuecomment-146560756",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/522",
    "id": 146560756,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjU2MDc1Ng==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-08T14:20:35Z",
    "updated_at": "2015-10-08T14:20:35Z",
    "author_association": "MEMBER",
    "body": "@ngoldbaum this is fixed in master, so installing notebook from master should do it.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146619453",
    "html_url": "https://github.com/jupyter/notebook/issues/522#issuecomment-146619453",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/522",
    "id": 146619453,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjYxOTQ1Mw==",
    "user": {
      "login": "ngoldbaum",
      "id": 3126246,
      "node_id": "MDQ6VXNlcjMxMjYyNDY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3126246?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ngoldbaum",
      "html_url": "https://github.com/ngoldbaum",
      "followers_url": "https://api.github.com/users/ngoldbaum/followers",
      "following_url": "https://api.github.com/users/ngoldbaum/following{/other_user}",
      "gists_url": "https://api.github.com/users/ngoldbaum/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ngoldbaum/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ngoldbaum/subscriptions",
      "organizations_url": "https://api.github.com/users/ngoldbaum/orgs",
      "repos_url": "https://api.github.com/users/ngoldbaum/repos",
      "events_url": "https://api.github.com/users/ngoldbaum/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ngoldbaum/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-08T16:50:50Z",
    "updated_at": "2015-10-08T16:50:50Z",
    "author_association": "NONE",
    "body": "@minrk thanks for pointing out the obvious to me, sometimes I need that :)\n\nSwitching to notebook master lets me get past the 405 error.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146805704",
    "html_url": "https://github.com/jupyter/notebook/issues/522#issuecomment-146805704",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/522",
    "id": 146805704,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjgwNTcwNA==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-09T08:57:46Z",
    "updated_at": "2015-10-09T08:57:46Z",
    "author_association": "MEMBER",
    "body": "@ngoldbaum thanks!\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/149610889",
    "html_url": "https://github.com/jupyter/notebook/issues/522#issuecomment-149610889",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/522",
    "id": 149610889,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0OTYxMDg4OQ==",
    "user": {
      "login": "zischwartz",
      "id": 77472,
      "node_id": "MDQ6VXNlcjc3NDcy",
      "avatar_url": "https://avatars.githubusercontent.com/u/77472?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zischwartz",
      "html_url": "https://github.com/zischwartz",
      "followers_url": "https://api.github.com/users/zischwartz/followers",
      "following_url": "https://api.github.com/users/zischwartz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zischwartz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zischwartz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zischwartz/subscriptions",
      "organizations_url": "https://api.github.com/users/zischwartz/orgs",
      "repos_url": "https://api.github.com/users/zischwartz/repos",
      "events_url": "https://api.github.com/users/zischwartz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zischwartz/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-20T15:48:19Z",
    "updated_at": "2015-10-20T15:48:19Z",
    "author_association": "CONTRIBUTOR",
    "body": "Hey, if this is still a problem for anyone else, it turns out we can address this from the clientside. Taking [this one line](https://github.com/oreillymedia/thebe/blob/master/static/services/kernels/kernel.js#L205) out of Thebe, seems to prevent the `OPTIONS` preflight altogether, and the backend deals with it fine. That's merged in Thebe on master now.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/149612727",
    "html_url": "https://github.com/jupyter/notebook/issues/522#issuecomment-149612727",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/522",
    "id": 149612727,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0OTYxMjcyNw==",
    "user": {
      "login": "rgbkrk",
      "id": 836375,
      "node_id": "MDQ6VXNlcjgzNjM3NQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/836375?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rgbkrk",
      "html_url": "https://github.com/rgbkrk",
      "followers_url": "https://api.github.com/users/rgbkrk/followers",
      "following_url": "https://api.github.com/users/rgbkrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/rgbkrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rgbkrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rgbkrk/subscriptions",
      "organizations_url": "https://api.github.com/users/rgbkrk/orgs",
      "repos_url": "https://api.github.com/users/rgbkrk/repos",
      "events_url": "https://api.github.com/users/rgbkrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rgbkrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-20T15:53:23Z",
    "updated_at": "2015-10-20T15:53:23Z",
    "author_association": "MEMBER",
    "body": "Oh awesome.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/149665785",
    "html_url": "https://github.com/jupyter/notebook/issues/522#issuecomment-149665785",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/522",
    "id": 149665785,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0OTY2NTc4NQ==",
    "user": {
      "login": "jdfreder",
      "id": 3292874,
      "node_id": "MDQ6VXNlcjMyOTI4NzQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3292874?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jdfreder",
      "html_url": "https://github.com/jdfreder",
      "followers_url": "https://api.github.com/users/jdfreder/followers",
      "following_url": "https://api.github.com/users/jdfreder/following{/other_user}",
      "gists_url": "https://api.github.com/users/jdfreder/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jdfreder/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jdfreder/subscriptions",
      "organizations_url": "https://api.github.com/users/jdfreder/orgs",
      "repos_url": "https://api.github.com/users/jdfreder/repos",
      "events_url": "https://api.github.com/users/jdfreder/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jdfreder/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-20T18:51:29Z",
    "updated_at": "2015-10-20T18:51:29Z",
    "author_association": "CONTRIBUTOR",
    "body": "Thanks for sharing that @zischwartz \n",
    "performed_via_github_app": null
  }
]
