[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/237210343",
    "html_url": "https://github.com/jupyter/notebook/issues/1651#issuecomment-237210343",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/1651",
    "id": 237210343,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIzNzIxMDM0Mw==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-03T11:19:59Z",
    "updated_at": "2016-08-03T11:19:59Z",
    "author_association": "MEMBER",
    "body": "It's working for me in master. I think this is tied up with the logging changes in ipykernel: ipython/ipykernel#127. If so, ipykernel 4.4 should fix it.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/237272717",
    "html_url": "https://github.com/jupyter/notebook/issues/1651#issuecomment-237272717",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/1651",
    "id": 237272717,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIzNzI3MjcxNw==",
    "user": {
      "login": "Carreau",
      "id": 335567,
      "node_id": "MDQ6VXNlcjMzNTU2Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/335567?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Carreau",
      "html_url": "https://github.com/Carreau",
      "followers_url": "https://api.github.com/users/Carreau/followers",
      "following_url": "https://api.github.com/users/Carreau/following{/other_user}",
      "gists_url": "https://api.github.com/users/Carreau/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Carreau/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Carreau/subscriptions",
      "organizations_url": "https://api.github.com/users/Carreau/orgs",
      "repos_url": "https://api.github.com/users/Carreau/repos",
      "events_url": "https://api.github.com/users/Carreau/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Carreau/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-03T15:29:18Z",
    "updated_at": "2016-08-03T15:29:18Z",
    "author_association": "MEMBER",
    "body": "Arguably it should abort the execution on the cell magic which does not exist. But agreed that on master there is at least a message. \n",
    "performed_via_github_app": null
  }
]
