[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/130352206",
    "html_url": "https://github.com/jupyter/notebook/issues/275#issuecomment-130352206",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/275",
    "id": 130352206,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEzMDM1MjIwNg==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-12T15:52:37Z",
    "updated_at": "2015-08-12T15:52:37Z",
    "author_association": "MEMBER",
    "body": "Try running `conda update pyzmq` first. I'm not sure why conda Python would be failing to build pyzmq.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/130372383",
    "html_url": "https://github.com/jupyter/notebook/issues/275#issuecomment-130372383",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/275",
    "id": 130372383,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEzMDM3MjM4Mw==",
    "user": {
      "login": "kprybol",
      "id": 10142795,
      "node_id": "MDQ6VXNlcjEwMTQyNzk1",
      "avatar_url": "https://avatars.githubusercontent.com/u/10142795?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kprybol",
      "html_url": "https://github.com/kprybol",
      "followers_url": "https://api.github.com/users/kprybol/followers",
      "following_url": "https://api.github.com/users/kprybol/following{/other_user}",
      "gists_url": "https://api.github.com/users/kprybol/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kprybol/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kprybol/subscriptions",
      "organizations_url": "https://api.github.com/users/kprybol/orgs",
      "repos_url": "https://api.github.com/users/kprybol/repos",
      "events_url": "https://api.github.com/users/kprybol/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kprybol/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-12T17:06:39Z",
    "updated_at": "2015-08-12T17:06:39Z",
    "author_association": "NONE",
    "body": "That seemed to fix the issue. Thanks. \n",
    "performed_via_github_app": null
  }
]
